### ISSUE TITLE
Fixed budget project

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1011]
**Is your feature request related to a problem? Please describe.**
We have projects which are charged at a fixed amount no matter if I spend 1 hour or 10 hours of work for the project.

**Describe the solution you'd like**
When creating a project, it would be great to have a field to enter the fixed amount. It does not necessarily have to be shown if a user records an activity for this project (or the field "rate" could show "fix"). However, for the invoice creation, there should be a key like ${project.fixed_amount} which would then show the fixed amount initially entered for the project when creating the invoice.

**Describe alternatives you've considered**
Add the fixed amount manually after creation of the invoice.

**Comment by kevinpapst** [comment]
Re-using the projects budget could be an option as well, as this is already available.
Then adding an "invoice sum calculator" could be adde, which uses the budget as a fixed rate.

**Comment by kindlyfire** [comment]
I would love to see fixed-price projects as well. For most of my freelance projects I charge a fixed amount agreed upon upfront. I still like to track my time, but the time itself doesn't matter. It seems like this is not something we can currently do

**Comment by acmeraptor** [comment]
Fixed price is on each customer, project, and activity setup page.

**Comment by kindlyfire** [comment]
I cannot see fixed price on the project edit dialog. I can see fixed rate, but that is different. With a fixed rate, the client is billed that rate each time I log a time period. What I'd like to achieve is that the project has its price, and the activities add nothing to it

**Comment by BeckeBauer** [comment]
> Re-using the projects budget could be an option as well, as this is already available.

@kevinpapst: Do you see any chance that the "projects budget" becomes a global variable - e.g. ``${project.budget}`` so that it can be used as template variable in the invoice document?

(unfortunately, I have no clue what your suggestion "adding sum calculator" means)

**Comment by kevinpapst** [comment]
@BeckeBauer sure. If you need it now, add the following code to this file and line:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/InvoiceModel.php#L316
```
                'project.budget_money' => $formatter->getFormattedMoney($project->getBudget(), $currency),
                'project.budget_money_nc' => $formatter->getFormattedMoney($project->getBudget(), null),
                'project.budget_money_plain' => $project->getBudget(),
                'project.budget_time' => $project->getTimeBudget(),
                'project.budget_time_decimal' => $formatter->getFormattedDecimalDuration($project->getTimeBudget()),
                'project.budget_time_minutes' => number_format($project->getTimeBudget() / 60),
```

**Comment by BeckeBauer** [comment]
@kevinpapst thank you, now the project budget value is shown in the invoice 👌👍!  (I leave the issue open since I still need to figure out how the value can be used for calculation in the invoice template, i.e. add VAT and total amount).

**Comment by sdillenburg** [comment]
I would like to have fixed price / lump sum projects as well. Would be nice to have a progress counter for each lump sum task where invoices can be issued monthly based on progress. The progress needs tp be updated maually, the amount on the invoice needs to be based on progress. Also, kimai would need to remember the ratio of the total amount already invoiced so that the total amount is reached when 100% progress is reached.
I still want to track the hours the normal way so that I can see how well progress and spent hours match.

**Comment by kevinpapst** [comment]
This request is too old and so many things have changed... I have many customers who used fixed price projects.
You can use the budget and/or the expense plugin or a combination of both.
Track the time with a rate of 0 but write invoices based on expenses. 
There are so many possible workflows and invoice handling issues. 

From my point of view all that you were missing 2 years ago might have been the option to enter arbitrary amounts for the invoice items. But that can be done via expenses now. 

So I am closing here, because ... no vote or comment for 2 years.
