### ISSUE TITLE
Export Files is not Downloading in webview app

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1061]
I am using kimai in my mobile (Android/IOS) App. While Downloading My Timesheet in Excel and Csv ., Its not downloading . But it Working on Print .,  I Have Issue in Exporting PDF #1048 But the error screen is also opening when am choosing PDF. I tried on Demo Website its also having same Issue in the app . I Given all the Necessary Permission and Functionalities to my app .

When i Tried Using another Downloading Website its working well .

**Comment by kevinpapst** [comment]
The buttons in Kimai are no links to a PDF, but they submit a form. 
Thats why you can't tap them longer to see more download options. 
Click Excel or PDF and then use the share menu when the file opened, to select the target app for the file or to save it.

**Comment by karthikalsv** [comment]
The file is not opening For Csv,Excel and PDF in the mobile app . It is Opening For Print .

**Comment by kevinpapst** [comment]
Can you please write more information in your issues and demonstrate the erros.
Include more information in general. You are posting one issue after another and expect free help, but don't want to spent a decent amount of time with your answers/request.
I don't see what you see and I can't read your mind, please try to find some artivles on how to write good reports.

I cannot reproduce what you are writing or I don't understand you. Its working for me.

**Comment by karthikalsv** [comment]
Well , I am Going to Use Kimai in Android/IOS App , Everything is working Fine in my case . But when i Like to Export my Timesheet in any Format(PDF,Excel,CSV,ODD) , Its Not Downloading or Opening the File  . When i Choose Print my Timesheet, Its Working Good .,

[https://github.com/kevinpapst/kimai2/issues/1061#issuecomment-524540360](url)

As You Said Before, Use Share Menu after file is opened, In My Case the files are not opening in my App  except print., When i Click any format.

**Comment by kevinpapst** [comment]
Aha, I missed the "app" part before. How is it working in Safari or any other mobile browser?

**Comment by karthikalsv** [comment]
Mobile Browser App is Working well. I developed an Native Android App, i Used my server url to use kimai . in that App only Its not opening . .

**Comment by kevinpapst** [comment]
Well, I don't know anything about native apps. I can help guessing:
If your app is using a native WebView (or however the component might be called) than the print view is likely working because its HTML.

But all other mimetypes are probably not supported, so I guess you need to intercept the download somehow and handle the file stream / binary response somehow. 

Here is one example of a response (as you can see a simple HTML reponse with some headers): 
https://github.com/kevinpapst/kimai2/blob/master/src/Export/Renderer/PDFRenderer.php#L71

If you find something that needs to be adapted in Kimai to support downloads, please let me know what. But I don't think that Kimai has anything to do with the problem.

**Comment by karthikalsv** [comment]
Ok . Thank You and Sorry For Asking Bunches of Questions Without clarity . I'll find out any other Solution for this issue and let you know. 

Thank you again .

**Comment by kevinpapst** [comment]
👍 Is the app only for you or do you want to put it in the stores?

**Comment by karthikalsv** [comment]
Its only for me .
