### ISSUE TITLE
Hide rows for Export

### ISSUE THREAD

**Issue by applejuiceDE** [kevinpapst/kimai2#1121]
Hello everybody,

I use Kimai v2 for some days now and I am very happy to see Kimai is developing further.
For invoicing I use another software, but I want to attach the exported timesheet form Kimai to my customers. Is there any possibility to hide the last row including the fee? Also I wonder if I could change the Layout.

Best regards

**Comment by kevinpapst** [comment]
Hi & thanks or posting!
Which export are you talking about?

**Comment by kevinpapst** [comment]
Ah right, okay. Because the "timesheet export" for me is this:
<img width="948" alt="Bildschirmfoto 2019-09-20 um 11 47 18" src="https://user-images.githubusercontent.com/533162/65317634-81c40880-db9c-11e9-8333-1da474dc581e.png">

You can add your own exporter: 
https://www.kimai.org/documentation/export.html#adding-export-renderer

You need to write your own plugin for that: 
https://www.kimai.org/documentation/plugins.html

You could change the PDF template, but that change will be gone after the next upgrade:
https://github.com/kevinpapst/kimai2/blob/master/templates/export/renderer/pdf.html.twig
