### ISSUE TITLE
Support LDAP nested groups

### ISSUE THREAD

**Issue by Aloz1** [kevinpapst/kimai2#1144]
**Is your feature request related to a problem? Please describe.**

Currently, Kimai is unable to pickup user membership of groups with LDAP when groups are nested. This makes Kimai integration a bit clunky in that users must be direct members of LDAP groups used in group/role mapping. Some LDAP setups (e.g. FreeIPA/IdM) emphasize nested groups for tidier policy management. FreeIPA in particular has different "types" of groups, (groups/roles/privileges/permissions). A minimal example LDIF has been included in the **additional context** section below.

Something worth noting is that reverse membership (memberOf) is automatically accumulated as you traverse up the hierarchy, which makes the problem much easier to solve efficiently (no need to do recursive lookups ourselves).

**Describe the solution you'd like**
For reverse group membership (memberOf attribute within users) to be allowed as an alternative to group membership within group/role mapping.

**Describe alternatives you've considered**
Group membership could be searched recursively...but this would likely have a large performance impact depending on how broad or deep the hierarchy is.

**Additional context**
An example LDIF file showing how nested groups are structured in FreeIPA:
```
dn: cn=Kimai Teamlead,cn=roles,cn=accounts,dc=example,dc=com
member: cn=webapps_admins,cn=groupss,cn=accounts,dc=example,dc=com
objectClass: groupofnames
objectClass: nestedgroup
objectClass: top
cn: Kimai Teamlead

dn: cn=webapps_admins,cn=groups,cn=accounts,dc=example,dc=com
memberOf: cn=Kimai Teamlead,cn=roles,cn=accounts,dc=example,dc=com
member: uid=aloz1,cn=users,cn=accounts,dc=example,dc=com
objectClass: groupofnames
objectClass: nestedgroup
objectClass: top
cn=webapps_admins

dn: uid=aloz1,cn=users,cn=accounts,dc=example,dc=com
memberOf: cn=webapps_admins,cn=groups,cn=accounts,dc=example,dc=com
memberOf: cn=Kimai Teamlead,cn=roles,cn=accounts,dc=example,dc=com
objectClass: person
objectClass: top
mail: aloz1@example.com
displayName: Aloz1
uid: aloz1
```

**Comment by kevinpapst** [comment]
Hi,
member support was included in the first version of the LDAP plugin, but I was told it is not often used, so it was replaced with the current solution.

I don't have a setup for testing and no need for it, but I think it should be rather simple to add it. If you want to work on it and contribute a PR, let me know. I can help with ideas.

**Comment by Aloz1** [comment]
Hi Kevin,

Alright, thanks for the quick response. I'm assuming that's #815 ? Unfortunately I'm really busy at the moment, and probably will be for a few months yet :(

If no one else picks up this issue in the mean time, I'll probably start working on a PR around early November.

**Comment by acmeraptor** [comment]
I doubt this will be beneficial now, but for my own setup I chose to split members between organizational units rather than subdivide members from one group to another all under one directory.  

You can essentially copy and paste users/roles within ldap. I've done it while testing phpldapadmin.  

I'm not sure a plugin is necessary for this.

Keep it simple.

**Comment by acmeraptor** [comment]
I'm not sure if my new problem is related to what @Aloz1 was experiencing, but I'm pretty sure my previous comment was out of scope.

Kimai2 is talking to my ldap server and seeing the users I have defined that are supposed to have access.  However, I have tried multiple times to make my defined group of users to have access to certain roles (in this case super admin) but they are defaulting to the basic user role.  Since I cannot mix permissions within kimai vs ldap, this may be an issue worth bringing up.  And I can start one if you want me to.

I really don't know if I am experiencing the nested group problem or inaccurate documentation.   I have also tried several suggested parameters for ldap syncing from the documentation links you have provided, to no effect.

**Comment by Aloz1** [comment]
@acmeraptor Unfortunately, FreeIPA abstracts away a lot of the "directory" nature of LDAP, and discourages direct access and modification through utilities such as phpldapadmin. The FreeIPA system integrates very tightly with LDAP, so modifying directory structure (adding new OUs, copying users around, etc) is generally unsupported and would likely break the system. Your solution should however work fine for vanilla LDAP setups, with complete control over your LDAP structure.

Regarding your second comment, not entirely sure what you're experiencing there, but it sounds like its a general missconfiguration problem, and not related to this feature request at all. Kimai automatically adds all users to the "user" role, so it sounds like your setup just can't read your groups.

It looks like Kimai doesn't have a support forum/IRC or equivalent at the moment, so perhaps for now you should open a new github issue for your specific problem (to prevent this issue from going off topic). If it does end up being related to this issue, it can be closed later as a duplicate of this.

**Comment by acmeraptor** [comment]
@Aloz1 It was merely a suggestion that I thought might help with the tools I personally have available.  My setup is very vanilla and is why I thought I was being helpful :)  But I am beginning to understand the complexity your situation.

I do have a configuration issue, and what you described is exactly my problem.  I cannot tell what part of my local.yaml is misconfigured though, which is why I mentioned documentaton.  I can see my users, I just cannot assign roles appropriately.  

I don't think it's a failure on coding on Kevin's part.  If this does become an issue, it should only be labeled for documentation. I need to work out the quirks first and then share the knowledge.

**Comment by Aloz1** [comment]
@acmeraptor All good, I'm aware it was a suggestion. I was merely elaborating on why it would not work for more complex setups :)

Anyhoo, if no one else has started working on this yet, I've now got time (so much for early November :P). I can hopefully have a PR ready in a week or 2.

**Comment by acmeraptor** [comment]
@Aloz1 I have done a fair amount of reading since then on LDAP.  I finally got mine to working.  But know enough now to not intercede anymore.,  I still have plenty to learn.  I don't think anyone else has even attempted the fix you have in mind yet.

**Comment by kevinpapst** [comment]
> Anyhoo, if no one else has started working on this yet, I've now got time (so much for early November :P). I can hopefully have a PR ready in a week or 2.

@Aloz1 announcing time estimations in the public is never a good idea 😁 let me know if you need help

**Comment by Aloz1** [comment]
Yes, you're quite right. My appologies, life has temporarily gotten in the way. Moving house, new job, all that fun stuff. I will let you know if I need any help.

**Comment by kevinpapst** [comment]
Topic has vanished I guess. Closing. You can open a new issue if this still a thing for you @Aloz1
