### ISSUE TITLE
Maybe: Conflict as Teamleader with missing user list

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#1157]
**Describe the bug**
Not sure, but I think a teamleader who can "edit_team" is not given a full list of users in the Team page and therefore will overwrite membership if saved there.

Or I couldn't find out what would let me get a list of users.
(Or I didn't grasp the concept yet)

If members-change-not-possible is intended, then the teamleader should not be given the right to save those.

**Additional context**
V 1.4

**Comment by kevinpapst** [comment]
I am not sure if that problem is new to 1.4 or was already there in 1.3. There was a code change in 1.4 which could have the side effect that a teamlead only sees the user of his teams. 

Interesting conceptual problem: should a teamlead should have the permission to edit teams. 
I highly doubt that and thats why it isn't set by default.

But if you allow it, then what should be possible?

I tried a fix, which seems the most logical to me: 
- If a teamlead has `view_team` and `edit_team` permission, he will only see the teams where he is the teamlead. 
- A teamlead will always see all users of his teams in all user lists
- As he can only edit the teams where he is the teamlead and sees all of his team members, he won't accidentally remove users when saving

I'll push a branch with that fix later.

**Comment by labor4** [comment]
i think the smaller issue is that when the form in the team page reflects all "local" team users, then the formsend wont brake. in my case that was the problem. however disabling a member, then that member is gone, AFAIK. i need an admin to fix it. 

if a teamlead should be a role to pick together people from outside the team then one needs a full user list. 

it's either the one or the other. 

but thats where i'm cautious with critics because i dont understand the full scope yet, meaning advantages/ disadvantages. my gut says as a teamlead i dont want to shape the team but manage only the jobs in it. 

i was thinking of defaults too. 
should a freshly created customer be automatically attached to a current team? it's a question to separate/strengthen the concept. i dont know the answer. 

cheers
m

**Comment by kevinpapst** [comment]
Concept wise, a (non-admin) user should only see own teams and team members. 

All the other points should be discussed in another topic.
