### ISSUE TITLE
Better workflow when creating project and team

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1238]
**Is your feature request related to a problem? Please describe.**
Only creating teams can controll access to projects, but in the workflow this are 2 different things.
Next problem: Many projects = many teams. Which team belongs to which project?

**Describe the solution you'd like**
1. When creating a new project set a checkbutton right of the name of the project for automatically creating an empty team.
Simple solution: Team name = project name
2. If checkbutton is set automatically change to team window for editing team members when project is saved.

With this solution new created projects are hidden for all users!

**Comment by kevinpapst** [comment]
Instead of the additional checkbox, I chose the way to add a project detail page (as you already know, but for other readers, same applies for customers):
- after creating a new project you come to a project detail page
- on that detail page you see all assigned teams (or none for new projects)
- there is a `+` button, which will add a default team with the current user being the teamlead and the name of the team = project name

See #1371
