### ISSUE TITLE
Project: orderDate timezone problem

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#1239]
**Describe the bug**

When setting the orderDate on projects, they are saved as UTC.
The original timezone is lost. 

Possible solutions:
- store only a date string
- store timezone

**Comment by wdenx** [comment]
Should not all times be saved in UTC in the database, but converted from / to local time in the UI upon entry / display?
In any case a date entered (when editing a project) must be displayed in the same way.
Storing the time zone is IMO not necessary as long as the same conversion from/to localtime is done everywhere.

**Comment by kevinpapst** [comment]
The problem is: what is the "local time"? 
Is it the servers timezone? Problem: e.g. shared hosts or misconfigured machines.
Is it the current users timezone? Problem: teams that work across the globe (the date can change).

**Comment by wdenx** [comment]
It should be the current user's time zone - because thisi s what he will use when entering data, and what he expects to see when looking at any output.
Yes, we also have distributed teams, and then it is even more important (actually that triggered my bug report) - think of a conference call: then you would expect that in the report all corresponding entries show the same times, even though each of the participants will log his local time.

**Comment by kevinpapst** [comment]
Seems I forgot to answer publicly:
Timesheets do handle timezones correct, this report is ONLY about the order-date field in projects.

**Comment by kevinpapst** [comment]
Fixed with 1.7
