### ISSUE TITLE
Archiv for Kimai

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1315]
**Is your feature request related to a problem? Please describe.**
Just started using of KIMAI but looking forward there will be the need to archive completed projects for preventing a steady growing database with finished projects/years.

**Describe the solution you'd like**
- Archiv in a parallel database with same structure
- Archiv as Excel or CSV file with projectname and date as filename.

**Comment by kevinpapst** [comment]
An archive is not planned, as you have multi options to hide entries: visibility => hidden or project end

**Comment by HeinzWuert** [comment]
And what about a steadily growing database over years? No deleting off old and further not needed entries?

**Comment by kevinpapst** [comment]
You can delete anything, that is no problem. 

Kimai runs on large setups with hundreds or thousands of records each week. I tested it with a couple of million entries without noticeable decrease in performance. I haven't tested it lately, because the last setup took more than 10 hours... but I actually don't see a good reason for the archive. 

If anyone wants to pay for it, I can have a look at it as plugin. But I don't see it as a core feature for Kimai. Its up to the user to decide what should be kept and what not.
