### ISSUE TITLE
User hourly rates and timesheets

### ISSUE THREAD

**Issue by amanzone** [kevinpapst/kimai2#1353]
Hi,

I'm not sure if and how I could achieve my goal.

In our setup we don't have Project/activity rates but only user hourly rates.
So the cost of one activity is simply the number of hours worked by each user on a specific activity multiplied by the user's hourly rates.

How is this achieved in Kimai?

I see that I can specify a user hourly rate in the preferences tab for each user, but I don't see this applied when evaluating (in "export", for instance) the project costs.

Also, how could I get the user hourly rate with the API, this seems to be missing.

Thanks for your help,
Alberto

**Comment by kevinpapst** [comment]
Hi!

> How is this achieved in Kimai?

You answered your question already and it is described in the documentation - how rates are calculated: https://www.kimai.org/documentation/timesheet.html#rate-calculation

> I see that I can specify a user hourly rate in the preferences tab for each user, but I don't see this applied when evaluating (in "export", for instance) the project costs.

I don't understand that. The rate is stored within each timesheet record and export/invoice (and every other calculation) will always use/display ONLY the rates that are stored in the timesheets.

So changing the hourly rate after recording will not change the already existing timesheets.

> Also, how could I get the user hourly rate with the API, this seems to be missing.

It is not (yet) exposed. 
You could duplicate this block and use `hourly_rate` instead of `timezone`:
https://github.com/kevinpapst/kimai2/blob/master/config/serializer/App/Entity.User.yml#L26

**Comment by amanzone** [comment]
Thank you, it's understood.
I was mistaken because we use a strange approach: we have desiged (even if it's just at an alpha stage now) a C# tool to pre-load all timesheets to a "placeholder" activity and then to re-assign all these timeshhets to the correct project.
So I was not seing these rates taken into account because when the placeholders timeshhets where created the hourly rates had not been defined yet, and then when the re/assignement was taking place, even if the rates had been defined in the meanwhile, they where not used only because the timesheet was not really changed, only assigned a different project.

Regarding the block you're pointing at, I assume this is a kimai configuration to define an item that could then be retrieved with the API.
If I do define the _hourly_rate_ item in this way, then how could I get the item's value with an API call?

**Comment by kevinpapst** [comment]
This config defines the values that will be shown when fetching user entities. 
The `groups: [User_Entity]` tells Kimai when this new attribute should be shown, search the controller for the occurence: https://github.com/kevinpapst/kimai2/blob/master/src/API/UserController.php
After changing these values, you need to clear the cache.

**Comment by amanzone** [comment]
Thnak you very much, that worked allright!
