### ISSUE TITLE
character problems in export PDF table header

### ISSUE THREAD

**Issue by gail7-github** [kevinpapst/kimai2#1433]
Kimai 1.7 i use hungarian language
Error description:
The UTF-8 characters not see in the export PDF table header. I attached a picture about the error.
[kimai-export.pdf](https://github.com/kevinpapst/kimai2/files/4146956/kimai-export.pdf)

**Comment by kevinpapst** [comment]
Someone needs to read the Fonts & Languages chapter in MPDF and find a fix.
I can help, but don't have the time to currently care about it.
 https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html

ping @infeeeee did you work with character encoding issues like these before?

**Comment by infeeeee** [comment]
The problem is the font used in the header of the table. These two characters are same, both of them are an `ő`, but it shows up in the title but not in the table header row:

![kép](https://user-images.githubusercontent.com/1271737/73656110-b63dea00-468f-11ea-8d50-7fcba19c2961.png)

I checked the ttf files in my install and it seems mpdf uses a lot of non utf-8 fonts by default. I can't figure out, which font is this, but I opened some of them randomly, and it's clear that some of them are not utf-8, you can see on this screenshot that they can't display `ű` and `ő`. This example can display `é`, so this is not the most problematic font:

![kép](https://user-images.githubusercontent.com/1271737/73656977-9c050b80-4691-11ea-9514-b1043758601c.png)

(This is a screenshot of the windows font viewer, this example text shows all accented Hungarian characters: árvíztűrő tükörfúrógép)

According to this documentation it's possible to overwrite the default fonts, however I can't find where this settings are applied in the kimai2 source code.

**Comment by kevinpapst** [comment]
Oh nice finding, thanks for the help 👍 

Here is the code that initializes mpdf: 
https://github.com/kevinpapst/kimai2/blob/master/src/Utils/MPdfConverter.php

And here is the template: https://github.com/kevinpapst/kimai2/blob/master/templates/export/renderer/pdf.html.twig

**Comment by infeeeee** [comment]
After some trial and error, it seems like the problem is not with the font but also with `font-variant: small-caps` [export/renderer/pdf.html.twig L39](https://github.com/kevinpapst/kimai2/blob/master/templates/export/renderer/pdf.html.twig#L39). 

Others already had this problem in 2017: [stackoverflow](https://stackoverflow.com/questions/42116675/small-caps-latin-characters-on-pdf)

But according to this issue it was fixed: https://github.com/mpdf/mpdf/issues/147

Everything works correctly without small caps: 
![kép](https://user-images.githubusercontent.com/1271737/73661924-3a499f00-469b-11ea-94a0-a71975b5d349.png)

I tried with most of the default fonts from mpdf, and characters also disappeared. I only found one font where it was showing, FreeMono, but I think it doesn't fit to the theme of the export. I tried to change this to bold, but then the characters disappeared again, but now they are question marks instead of empty boxes...

![kép](https://user-images.githubusercontent.com/1271737/73662386-002ccd00-469c-11ea-94a1-38eb2b571fa4.png)
![kép](https://user-images.githubusercontent.com/1271737/73662582-5e59b000-469c-11ea-81f0-267b8f88d504.png)

So possible solutions:

1. Remove the small-caps, and replace it with some different styling, maybe bold and bigger font-size, this example is  
```
font-weight: bold; 
font-size: 11pt;
```

![kép](https://user-images.githubusercontent.com/1271737/73663105-3b7bcb80-469d-11ea-85f4-8406f1d59234.png)

2. Read more in the mpdf docs, and try to find a better solution.

**Comment by infeeeee** [comment]
And it affects every languages, this is in czech: 
![kép](https://user-images.githubusercontent.com/1271737/73663570-25bad600-469e-11ea-9010-683ec9e9f916.png)

**Comment by kevinpapst** [comment]
As the small-caps setting was just copy&paste and not because I deeply care about how it looks 😁 I say we go with your solution 1 and simply change the css. 

Do you want to submit add a PR for that?

**Comment by kevinpapst** [comment]
Oh: and big thanks for taking the time to investigate this issue!!!!

**Comment by infeeeee** [comment]
I will do it, in a second

**Comment by gail7-github** [comment]
Many thanks! The Kimai is awsome!
