### ISSUE TITLE
Summary of time entries in timesheets

### ISSUE THREAD

**Issue by HonzaKopecky** [kevinpapst/kimai2#1481]
**Is your feature request related to a problem? Please describe.**
Maybe I am just missing some settings but I just cannot find it. Is there really no way to get number of hours / rate count on the Timesheet screen? Do I need to use the Invoice functionality to get this simple sum?

**Describe the solution you'd like**
Two widgets above all timesheet entries that would state the sum of time and sum of all rates for the currently filtered entries in the Timesheet screen.

**Describe alternatives you've considered**
I understand it is a bit more difficult because of different currencies that can be in the timesheet but this information is quite crucial in our case. 

**Additional context**
Would you accept a solution where the two widgets from Dashboard would be just added above the Timesheets table? The only modification that would need to be done is that the widgets would accept the filter criteria that the user supplies using the search form.

**Comment by kevinpapst** [comment]
Just showing the widgets would look stupid.
Displaying the same number (sum of all recorded hours) in 95% of all cases is rather useless, so there needs to be a setting to remove it. And it should be a solution that can be applied to all screens.

The numbers are missing because I would like to see them in a new "reporting" screen.

This is a duplicate, please search for already existing issues.
