### ISSUE TITLE
setCustomer() must be an instance 

### ISSUE THREAD

**Issue by sofiendamiP** [kevinpapst/kimai2#1539]
I am facing this problem while importing data from Kimai v1.
Can anyone help me ?
<img width="681" alt="Bildschirmfoto 2020-03-09 um 13 04 57" src="https://user-images.githubusercontent.com/58558892/76399004-2bcb6300-637e-11ea-8101-e9d9c27bae59.png">

**Comment by kevinpapst** [comment]
When I copy your error message into the search I get immediately this result:
https://github.com/kevinpapst/kimai2/issues/1519#issuecomment-596757013

**Comment by sofiendamiP** [comment]
Thank you so much for your fast response. 

I have tried that but it didn't work for me.
His message showes a problem on line 750 but mine on 684.

**Comment by kevinpapst** [comment]
The line doesn't matter. I guess you are trying Kimai 1.8. The file has changed since then. The user in the linked issue used "master", which is the latest developer version. 
There is only one place where this code is called.

You have a project in Kimai v1, that has an empty/not-existing customer.

**Comment by kevinpapst** [comment]
[KimaiImporterCommand.php.zip](https://github.com/kevinpapst/kimai2/files/4319126/KimaiImporterCommand.php.zip)
If you replace the attached file (after unzipping) with the one on your server at src/Command/KimaiImporterCommand.php then Kimai will tell you which project has the problem.
