### ISSUE TITLE
Database import from Kimai 1.3.1

### ISSUE THREAD

**Issue by deobokl** [kevinpapst/kimai2#1573]
When I start the database import from the old version it stops with the error: Attempted to call an undefined method named "setHourlyRate" of class "App\Entity\Project".

**To Reproduce**
I used the command recommended in the documentation:

bin/console doctrine:schema:drop --force && \
bin/console doctrine:schema:create && \
bin/console kimai:import-v1 "mysql://kimai:test@127.0.0.1:3306/kimai?charset=latin1" "kimai_" "test123" "CH" "CHF" --timezone="Europe/Zurich" --language="ch"

In KimaiImporterCommand.php line 727:

 - Kimai version old 1.3.1 new 1.8 fresh install
 - PHP version 7.3

**Comment by kevinpapst** [comment]
Already fixed in master. Either switch to master or replace this file in your installation: https://github.com/kevinpapst/kimai2/blob/master/src/Command/KimaiImporterCommand.php

**Comment by deobokl** [comment]
I used the command line install – so it should be the right version or not?

**Comment by kevinpapst** [comment]
You have 1.8, the version which contains that `Attempted to call an undefined method named "setHourlyRate" of class "App\Entity\Project". ` bug. 
The bug itself was already fixed, bBut there is no new release available that contains the bug. 
So you have to copy&paste the updated file to your installation in order to use that fixed version.

**Comment by deobokl** [comment]
ok that worked

**Comment by deobokl** [comment]
another question – seems that css files are sometimes not loaded – when I see the login screen it looks ok, but after login styles are gone
<img width="1234" alt="Bildschirmfoto 2020-03-19 um 16 38 44" src="https://user-images.githubusercontent.com/24987486/77089801-9297ee80-6a06-11ea-9682-08efc01d00a0.png">

<img width="953" alt="Bildschirmfoto 2020-03-19 um 16 38 52" src="https://user-images.githubusercontent.com/24987486/77089796-90359480-6a06-11ea-838e-52f7d62a0ee2.png">

**Comment by deobokl** [comment]
Rights are 755 for all folders and docs

**Comment by kevinpapst** [comment]
Don't know. Maybe a browser plugin?
Check your browser console to see if there is an error and if so, which one.

**Comment by deobokl** [comment]
it happens in different browsers

**Comment by deobokl** [comment]
Keine der "sha384"-Hashes im "integrity"-Attribut stimmen mit dem Inhalt der Subressource überein.

**Comment by deobokl** [comment]
It look its because of this file: 0.f7fae2b9.js:1:3220

**Comment by kevinpapst** [comment]
No. That is not a problem in Kimai, its your environment.
The last time this was reported was because of a server plugin, I think it was pagespeed.
But it might also be a browser plugin or something like cloudflare or a proxy as well. The file you receive is not the original version that comes with Kimai, something changed it in between. Thats why the hash compare fails.

**Comment by deobokl** [comment]
yes thats it – so no way to get it work with page speed activated?

**Comment by deobokl** [comment]
thanks for the quick response!

**Comment by kevinpapst** [comment]
never used it, so I don't know if you can configure it to not touch the assets.

do you feel any difference between using it or not?
this plugin might be great with a wordpress site that uses 20 different javascript files. 

but kimai already ships highly optimized assets, so I doubt that it will improve the loading speed dramatically.
