### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by winternet-studio** [kevinpapst/kimai2#1584]
**Describe the bug**
I installed Kimai on a shared (Linux) server and the first page load after not having used the system for a while is always very slow, like 7-10 secs. Then subsequents request are fairly ok until I let it sit again for a while.

**To Reproduce**
As I can't do much tracing on the shared server I copied the system to my local developer machine (Windows). I don't see the exact same pattern but when I eg. click the Play icon to start a new timesheet it takes like 5-6 secs to load the dialog box.

**Logfile**
`prod.log` is empty. But I used xdebug to do a trace and it gave me the attached file - where according to my eyes the most notable is the last few lines that really take up a lot of time.

[trace.3880537610.txt](https://github.com/kevinpapst/kimai2/files/4369195/trace.3880537610.txt)

**Additional context**
 - Kimai version 1.8
 - PHP version on Windows is 7.3.10. On Shared Linux server 7.2.29.
 - I have no warning icons under the Doctor menu.

Is there any way I can speed up Kimai?

**Comment by kevinpapst** [comment]
Thanks for sharing your findings!
Xan you share your xdebug settings, so I can verify that?
I can't believe that the shutdown should take > 2.5 seconds. And by then, the output should already be on its way to your browser (at around 1.5 seconds - still too slow though).

There is likely room for improvements both: application wise and in PHP settings. The latter one might be hard on a shared host though...

How is your local setup? Windows with PHP 7.3, but which webserver? 
Any idea about opcache settings?

**Comment by winternet-studio** [comment]
I'm using only default xdebug settings (v2.8.0)...

I'm using Apache 2.4 with a pretty much out-of-the-box setup... with .htaccess enabled... The shared host is also using Apache.

opcache is builtin to PHP since 5.5 so there is nothing special there.

Any options in the application I can tweak so see if it makes any difference?

**Comment by kevinpapst** [comment]
Opcache is built-in, yes, but the amount of files and memory is limited.
If "Kimai" gets removed from the cache, because other sites are visited more frequently (on the shared host) this might be a reason for the delay.

First time when a page is opened, the template will be compiled. So this is the delay you are seeing. But it shouldn't happen on subsequent calls.

There are no Kimai specific settings that can be changed. On the technical side, some minor improvements can be made for sure, but I am not directly aware of any config settings that are related. Have a look through config/packages/ and config/packages/prod/ - maybe you can tune the DB caches or alike. If you have Redis on your hand, you could cache everything in there, which should be faster than filesystem caching, but honestly: the times you are seeing are not normal. 
On my server, calls to the most expensive pages (dashboard -most db calls and timesheets - a lot of data)are almost instantly there. Same for my dev environment - with debugging enabled the pages take 2 seconds (including the collection of symfony profiling data).

**Comment by adrianrudnik** [comment]
What kind of shared hosting is this?

Could you attach a `<?php phpinfo();` or on a shell `php -i` print?

If you go to `/de/doctor` on your instance, can you confirm that

a) Environment variables indicate that `APP_ENV` is running as `prod`?
b) File permissions are all marked green?

The env role `prod` should only compile the cache once, so this should not be a problem of cache regeneration. It might be `opcache.enable` being `off`, `opcache.memory_consumption` being too low (should be 64-128MB), `opcache.revalidate_freq` and `opcache.validate_timestamps` being activley rescanning files often on a production system.

Sometimes a default setting on `realpath` related stuff is at fault. The default values are not recommended to run a symfony project:

```ini
realpath_cache_size = 16k
realpath_cache_ttl = 120
```

but should be increased [considerably](https://symfony.com/doc/current/performance.html) to at least

```ini
realpath_cache_size=4096K
realpath_cache_ttl=600
```

but be aware that on a shared hosting with `open_basedir` in effect will never benefit from this. This can and will lead to very high pre-warming phases when the opcache loads the full autoloader and files from the filesystem. It can help to run `composer dump-autoload --no-dev --classmap-authoritative` and maybe even with `--apcu` if you can and have apcu compiled and active to work around that.

How to work around that in a very cheap manner? Use a cron that keeps the opcache / file cache warm. Install a cron that calls the `/de/login` path via curl and pipes it into /dev/null every 1-5 minutes. That should trigger most in-memory caches. Not the nicest way but shared hosting is bad enough as it is most of the time.

PS: You do not have a prod.log on your productive system? Can the webserver write to the `var/` directory?

**Comment by PjotrDumat** [comment]
FYI Activating opcache today made it a lot faster in my case. Tnx !

**Comment by kevinpapst** [comment]
Closing here, as it was a configuration issue of the host machine.
As there are some important notes here from @adrianrudnik I created a [link from the FAQ](https://www.kimai.org/documentation/faq.html#kimai-is-slow) to this issue, so they won't be lost.
