### ISSUE TITLE
Optical error when deleting roles

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1588]
**Describe the bug**

-Create a new role
-Assign them to a user
-Delete this role
It then disappeared under Roles, but it remains in the user overview.
To prevent this, I would have had to revoke the role from the users first and then delete the role myself.
When deleting a role, there does not seem to be a comparison with the corresponding data field of the user.

**Comment by kevinpapst** [comment]
What happens if you update the user?

**Comment by HeinzWuert** [comment]
Sorry, cant check it anymore. Created the user roles once more, than it was possible to revoke the role from the user and after it I deleted the role. So my users a now "clean".
It`s no important bug.

**Comment by adrianrudnik** [comment]
@kevinpapst  The user can not be updated anymore because the validator fails: `This value is not a valid role.` but the deleted role will not be listed anymore as it no longer exists. User gets stuck as far as I can see. The old role name from the `kimai2_users.roles` column is still shown in the `admin_user` route.

`App\Repository\RoleRepository::deleteRole` should ensure that either all users get the role removed of throw an error if any user still has the role, what do you think?

**Comment by kevinpapst** [comment]
Both solutions are fine for me, even though it would be nicer if we remove it automatically from all users. Stupid problem: this column (managed through FosUserBundle) is a serialized array, which makes it painful... 

I throw in another solution: add a data-transformer which removes non-existing roles silently in https://github.com/kevinpapst/kimai2/blob/master/src/Form/Type/UserRoleType.php

**Comment by HeinzWuert** [comment]
for me this solution would be perfectly sufficient

**Comment by kevinpapst** [comment]
Okay, the only real solution is to update all users when a role is deleted, because the user profile could not be updated any longer due to the `This value is not a valid role.` validation error.

Fix see #1640
