### ISSUE TITLE
Beta: Strange behavior of TAG

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1627]
**Describe the bug**
If you create a TAG it will not be shown. Instead, the existing list with the many entries appears without the new entry.
If you click on Search, the newly entered TAGs appear.

**To Reproduce**
Tested as admin with TAGs aaa and aaa1

**Comment by kevinpapst** [comment]
Hm, the order is not case insensitive: `a` follows `Z`. 
If you try with `AAA` and `AAA1` you will see them without changing the page

**Comment by HeinzWuert** [comment]
Yes I see, but what is the sort button above the tag name for?
I would have expected an alphabetical order here.

**Comment by kevinpapst** [comment]
This is alphabetical ordering, but not case insensitive. Thats because the demos are running with SQLite. 

Try it in our live system and it will behave as you expect it, because Mysql uses a case insensitive collation. Closing this issue as it is SQLite specific behavior which I do not intent to fix.
