### ISSUE TITLE
No per user invoices

### ISSUE THREAD

**Issue by georgeowell** [kevinpapst/kimai2#1734]
## Describe the bug
We're a workers co-op of freelancers and we invoice our business individually for our wages. The problem is, we can't work out a way to do per-user invoices. 

When we try and generate invoices, they include the activities of all the different users together. It would be super useful to be able to generate an invoice with only the activities your user has done on it as you can with time-sheets.

I checked all the docs. Am I just missing something or is this not possible?

### Possible complicating factors
- All of us are in the same team
- All of us are admins

### Possible solutions
- We each have our own team
- We each have our own customer (all the same details for our business)

## To Reproduce
Steps to reproduce the behaviour:
1. Try to export any invoice
2. You can see that the invoice generated includes activities from all users

**Comment by kevinpapst** [comment]
Kimai 1.9? Does our invoice form look like this:
<img width="749" alt="Bildschirmfoto 2020-05-24 um 16 06 48" src="https://user-images.githubusercontent.com/533162/82756142-95cda300-9dd8-11ea-82d1-884c0f1d203c.png">

If you see only 4 fields, click the cogs icon and deactivate "simple search".

**Comment by georgeowell** [comment]
Yes sorry. Version 1.9. Awesome that's solved that issues perfectly. Perhaps a few lines about this feature in the Invoices part of the documentation? 

Perhaps you have already solved this though in development so I will won't close issue yet.

**Comment by georgeowell** [comment]
Oh wait sorry. I spoke too soon. Even if I select only my own user, I still activities from others :crying_cat_face:

**Comment by kevinpapst** [comment]
I guess the deleted post means that it works?

**Comment by kevinpapst** [comment]
The "simple search" config was a test and I guess it needs to be reverted, as it is not obvious (you are not the first one to ask that).

I have to change that, not sure about how...

**Comment by georgeowell** [comment]
Yep this is solved. Thanks so much @kevinpapst 

(^ .^)/

**Comment by Randelung** [comment]
Quick note, since it fits.
I was looking at how to filter activities. Your post above with "simple search" obviously helped, thank you.
I'd like to add that only administrators can access that option. As team lead I'm not able to change it. I can see why - changing the setting changes it for everyone (which in my case is perfectly fine).
Have you considered switching based on user preference? A cookie like in column visibility would be adequate.

In the Invoice section of the documentation you mention an activity filter (in the template part). There's no screenshots or any mention of this simple search feature. May I suggest amending the documentation with basically your post above?

Generally, though, thank you for making Kimai. Personally, I'm a long term user, and I'm now trying to introduce it at work.

**Comment by kevinpapst** [comment]
Reopening, so it won't get lost

**Comment by kevinpapst** [comment]
Default setting is now (in v1.10) back to "full search" with the option to activate the simple search individually.
