### ISSUE TITLE
Kimai2 Installation "successful" but not starting

### ISSUE THREAD

**Issue by mauricebar** [kevinpapst/kimai2#1749]
I installed Kimai2 in a Synology DS718+ with DSM 6.2.2-24922 Update 4. I installed according the instructions for Synology and general guides. This is a new installation and therefore I did not do anything related to migration steps from older versions of Kimai.

After installing I got a successful message and when I open the Kimai Site I get this message: "Something is wrong
A critical error has occurred. You may have found a software error, please contact your administrator if the error persists."

**To Reproduce**
I installed from scratch everything.
1. Cloned repo 1.9 with git
2. Installed composer: https://medium.com/unhandled-code/installing-composer-on-synology-6-1-4-eebd1a1c4891 
3.  Created an SQL DB in phpMyAdmin (MariaDB v10)
4. Configured the database connection in the .env file
5. Ran the installer
6. Pointed the web server to public/ 
7. Additional settings in the specific nginx/conf.d directory
8. Checked the nginx withsudo nginx -t and was successful
9. Reloaded nginx
10. TESTED --> described error (500)
11. Changed the file permissions
12. Tested again, same error

**Logfile**
```
I was not able to find this file: var/log/prod.log. It is not in this directory, there are other files but not this.
```

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: Synology DS718+
 - OS:  DSM 6.2.2-24922 Update 4
 - Browser Firefox 76.0.1 (64-Bit)

**Additional context**
 - Kimai version 2
 - PHP version 7.3
 -DB MariaDB v10
 -phpMyAdmin (PHP 5.6)

![grafik](https://user-images.githubusercontent.com/65902071/82889195-aaca4380-9f4a-11ea-8b99-62e239fe606a.png)

**Comment by kevinpapst** [comment]
Are you sure you looked in `kimai/var/log/` and not in `/var/log/`? 
There should be no other files except the `prod.log` (besides a `.gitkeep` file).
If you were in the right directory, this is very likely a permission problem.

**Comment by mauricebar** [comment]
That was a novice mistake, sorry. I was in the oder folder. The log is here.
[prod.log](https://github.com/kevinpapst/kimai2/files/4682697/prod.log)

**Comment by kevinpapst** [comment]
As I said, that’s a permission problem for var/cache/

**Comment by mauricebar** [comment]
Kevin, thanks a lot. I run the commands the last week but probably I did run them also in the incorrect folder. Now it works! thanks a lot!

**Comment by kevinpapst** [comment]
Great, thanks for the feedback!

**Comment by PartapS08** [comment]
Need help ! getting same error and not able to fix.
Environment [local VM, Redhat7.9, Mysql5.7, PHP7.3, HTTP2.4]
Followed : https://www.kimai.org/documentation/installation.html#recommended-setup

one extra-step : php bin/console doctrine:schema:update --force --complete --dump-sql
because of getting : [ERROR] The database schema is not in sync with the current mapping file. 

Permissions looks ok, also tried setting 777 on var/cache/. still same error.

prod.log : 
[2020-10-13 08:30:56] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\HomepageController::indexAction","_locale":"en"},"request_uri":"http://192.168.56.108/en/homepage","method":"GET"} []
[2020-10-13 08:30:56] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Driver\PDOException: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai2.kimai2_sessions' doesn't exist" at /app/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 123 {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai2.kimai2_sessions' doesn't exist at /app/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai2.kimai2_sessions' doesn't exist at /app/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []

Thanks

**Comment by rg-ch** [comment]
I have the same screen doing "successfull" upgrade from 1.2 to 1.11,

I think there is effectively  a missing table  .....

**kimai2_sessions** 

`[2020-11-27 12:36:26] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Driver\PDOException: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ldup_km2.kimai2_sessions' doesn't exist" at /home/clients/59fbcddb5b62030fc94c44cd670c7d77/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 123 {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ldup_km2.kimai2_sessions' doesn't exist at /home/clients/59fbcddb5b62030fc94c44cd670c7d77/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ldup_km2.kimai2_sessions' doesn't exist at /home/clients/59fbcddb5b62030fc94c44cd670c7d77/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []
`
![image](https://user-images.githubusercontent.com/53338378/100447785-7da14e00-30b1-11eb-8d49-f214902a0446.png)

Is it possible to create this table afterwards

**Comment by kevinpapst** [comment]
Necromancy => locking thread.
Open a new issue for your problem
