### ISSUE TITLE
Add allowance percentage to invoice

### ISSUE THREAD

**Issue by kymeyer** [kevinpapst/kimai2#1848]
**Describe the solution you'd like**
Our projects set hourly rates and on top of we will charge a percentage (e.g. 3%) of the net-total for general expenses. It would be great if kimai could include an option for such a task.

**Describe alternatives you've considered**
Is that possible with the expenses Plugin? We do not wish to add fixed expenses.

**Comment by kevinpapst** [comment]
The expenses plugin is not capable of doing such a task.

You could create your own invoice template using Excel or Twig, both are capable to calculate and add rows like you wish.
If you have development knowledge you could create your own "invoice calculator" - but that would need a plugin and is more complicated than changing the template.

**Comment by kevinpapst** [comment]
Two ideas came to my mind:

1. Adjust your invoice flow. Filter the customer/project in the invoice screen and get the sum, open a new tab and create manually an expense with the amount of 3% from the original sum, back to the invoice screen: click preview again, the expense is added. Generate the invoice.

2. Maybe you could fake it using a second tax rate (which is not yet existing) and a custom invoice template. 
You could vote for #1849 which talks about that.

So I am closing this issue here as no feedback came and I will not add such a feature to the core of Kimai. 
Why? Because almost every company has one or two special requirements for the invoice system and Kimai simply cannot cover all of them. Thats where custom invoice templates come into play and the highly customizable invoice API (which needs development knowledge / [a custom plugin](https://www.kimai.org/store/kevinpapst-custom-plugins.html)).

If a couple of people will leave feedback here, I will consider to reopen this.

**Comment by kymeyer** [comment]
Thank you for the ideas,

 i have been been able to try so far:

- change to a custom invoice template on basis of the docx template and adding whatever we need based on the replacers in the docu. No problems with that, works quite well.
- adding my own invoice calculator to do the necessary calculations. Here I provided a new file in APP/Invoice/CalculatorInterface and translations to invoice-calculator.xx.xlf. No errors when clearing the cache of the application, however, the new calculator does not show up in the dialog of the app to be selected. Any hint on that?

**Comment by kevinpapst** [comment]
No idea, I guess you have a mismatch between class name and filename / namespace. Then it wonÄt be picked up automatically

**Comment by kymeyer** [comment]
... solved it using a custom invoice template, adding an invoice calculator and working with custome replacers.

**Comment by kevinpapst** [comment]
Wow, nice work! And thanks for your feedback 👍
