### ISSUE TITLE
Listexport of generated Invoices from a certain state

### ISSUE THREAD

**Issue by sgaechter** [kevinpapst/kimai2#1955]
I' missing a list export for all created >Invoices from a certain state. 
These are my "wishes" for it:
- The List columns are ideally customized to the needs of everyone or containing all Fields of the Invoice-Table.
- The Listexport's filetype is ideally customizable or *.csv
- The List can be taken from "/invoice/show/" on the frontend by choosing the needed state and the needed Datediff
- The List can be produced containing the just generated Invoices by CLI-command by adding an additional flag (ex. -r or --report)

I'm willing to pay a "bounty" of 50Euro for the first Developer implementing this (as a plugin or as a feature) in Kimai2 for the public and sending me pre-release a message to beta test :-)

**Comment by vic-t** [comment]
From what I've seen, currently, it's not possible to export information about created invoices, there isn't even an API call.

If I should decide to use Kimai for invoicing, I will need to export information about these invoices in order to import the same in my accounting system from where I can then manage payments and payment reminders.

Clearly, Kimai saves the necessary information in the database, there already is a table named kimai2_invoices. So, as a temporary alternative, I can just create a CSV export from the database directly. But it would be nice if an invoice export functionality could be built into the Kimai frontend.

The author here requests an export with some very specific functionality but it seems to me that exporting invoices or referencing them via API should be part of the official product.

Anyway, I'd be happy to match the bounty offered by the OP in the other post to support the developers with this task. (I never worked with bounties so I'll need some info on the funding process).

**Comment by kevinpapst** [comment]
You can test the new search and export function.
This functionality is only available via the UI right now.
More infos at #2408

**Comment by sgaechter** [comment]
Well done. Exactly what I've expected. Bounty is payed :-)

**Comment by kevinpapst** [comment]
Thanks @sgaechter 👍 I know you had some very specific requests, but I want Kimai to be (as far as possible) work the same way in all places. Makes it easier for me in the long run. 
If you find any issue, pleas let me know
