### ISSUE TITLE
Add equivalent to row.nr variable to templating system

### ISSUE THREAD

**Issue by kernie** [kevinpapst/kimai2#2023]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
In Kimai v1 there was a variable "row.nr" that would simply put an increasing number to the timesheet entry of the query. If I'm not mistaken this functionality is not (yet) available in Kimai v2.

**Describe alternatives you've considered**
I'm using a docx template, so I cannot not use cell functions like in spreadsheet applications.

**Comment by kevinpapst** [comment]
Did you try number formatting of table cells? There is a feature in Word existing for, even though I have never tried it and can't say if it works with invoice templates...

**Comment by kernie** [comment]
Well, didn't know of that, but tried in LibreOffice Writer. It seems to have some formulas for tables. Not sure though, whether I have all functions at hand to do this simple thing.

I will try to get around.

Thanks!

**Comment by kernie** [comment]
Can you point me to the Kimai file where I could implement it? Maybe I can make a PR, when i find some time...

**Comment by kevinpapst** [comment]
I meant a formula that is added directly to your invoice template (I guess you meant invoice templates, right?) instead of patching Kimai. I would prefer that, instead of adding another field.
Having an increment number is only useful if you use the "one row per record" calculator.

But as last solution you could add it here: https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Hydrator/InvoiceItemDefaultHydrator.php#L61

**Comment by kernie** [comment]
Yes, I caught that... And it worked in libreoffice writer with a formatted list in the table. Didn't know that was possible.

So, I think we can close here.

Thanks for the suggestion.

**Comment by kevinpapst** [comment]
Thanks for the feedback!
