### ISSUE TITLE
Custom-fields plugin issue

### ISSUE THREAD

**Issue by ctpntn** [kevinpapst/kimai2#2069]
**Describe the bug**
Unable to assign the field by role but predefined ones
**To Reproduce**
1. Create a custom field 
2. Assign the custom field to Permission role different from the predefined ones (i.e. TEST_ROLE created previously)
3. The users with the permission TEST_ROLE are unable to see the custom field.

**Comment by kevinpapst** [comment]
Hi @ctpntn 

if you send me the gumroad recipe via email ([see blue box at this page](https://www.kimai.org/documentation/buy-a-plugin.html)), I will invite you to the repository of the plugin. Thats a better place to discuss these issues.

If you create a role that is called `ROLE_TEST` instead of `TEST_ROLE` it will work. Thats a known limitation of the security system of the used framework, which needs to be documented. Sorry for the troubles!

**Comment by ctpntn** [comment]
I sent you the recipt email.
AC

**Comment by kevinpapst** [comment]
Clarified in plugin repository
