### ISSUE TITLE
auto select customer on project selection ( and maybe improve keybinding)

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2317]
**Is your feature request related to a problem? Please describe.**
* when selecting a project with unique name  , the assigned cusomer has to be selected as well 
  ( the project selection dropdown already shows where the projectb belongs
* selection of the fields in the "new time-entry form"  is like:
  `ENTER`->`select(e.g. with a-z or arrow)`->`TAB`->`ENTER`

**Describe the solution you'd like**
* customer is filled in when selecting a project ( or even activity that is only used once )
* it should be possible to only use tab and have the dropdown/select item already actively focused  , so the field is ready to accept keys without `ENTER`
* maybe make a generous shortkey binding ( like youtrack  ) , this greatly improves speed in filling out

**Comment by vic-t** [comment]
Hi @bash-stack , just replying to the part "selecting a project with a unique name, the assigned customer has to be selected as well". 

I'm not sure this is an issue. It's actually not possible to create a project without assigning a customer to the project. In turn, when you create a timesheet entry for a specific project, it is not necessary to also select the customer because this information is already implied. 

It's true that the customer drop down box will not be populated but the customer name will still be part of the timesheet entry when you save it. You can easily verify this for yourself.

**Comment by kevinpapst** [comment]
The next version #2902 will use another JS library for dropdowns, which allows direct tabbing.

If you want keybinding, please contribute some ideas with details or even better: a PR 😄
