### ISSUE TITLE
Export Timesheets PDF online approval 

### ISSUE THREAD

**Issue by rjayaser** [kevinpapst/kimai2#2428]
**Is your feature request related to a problem? Please describe.**
When exporting the timesheets based on user, any feature to approve the timesheet before exporting.
![timesheet_approval_feature](https://user-images.githubusercontent.com/67286004/111033838-1f6a6200-8439-11eb-805a-7da7910a8c7a.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Screenshot**
Add a mockup / screenshot of your idea here.

**Comment by rjayaser** [comment]
[
![exporting_user_timesheet](https://user-images.githubusercontent.com/67286004/111034092-0c0bc680-843a-11eb-9984-86693eeb5c96.png)
](url)

**Comment by kevinpapst** [comment]
There is no approval process available in Kimai.

There is instead the lockdown period feature, which allows you to "close records for editing" based on the date. You find that in the documentation under timesheets.

I am closing, because I have no plans to add that feature, at least not in the next 1-2 years.
