### ISSUE TITLE
Auto Checkout if an User forget

### ISSUE THREAD

**Issue by GoProAndy** [kevinpapst/kimai2#2539]
Hi,
can you please add an feature to auto-checkout all users at a configuable time if they forget to checkout?
thanks
Andy

**Comment by kevinpapst** [comment]
I am not a big fan of that idea. I'd say: rhis has to be clarified 1:1 with the employee, because only he knows when he left.
Any auto-logout will always trigger at the "wrong time".
But this would be a opt-in feature always -  and I don't have to personally like every feature 🙈 so: accepted as feature request.

**Comment by pbksol** [comment]
> can you please add an feature to auto-checkout all users at a configuable time if they forget to checkout?

Easiest solution would be to use the API to stop time tracking and run this periodically. Just request all running timers and stop them one by one. Doing it this way you can define situations in which the timers should not stop (eg. never stop the timer if the user is still logged into his computer, is still on site or such).

**Comment by kevinpapst** [comment]
And you can use a bash script to stop all timesheet e.g. at midnight with this command:
https://github.com/kevinpapst/kimai2/blob/master/src/Command/TimesheetStopAllCommand.php

```bash
bin/console kimai:timesheet:stop-all
```

There are many ways of achieving this. 

Closing, as I do not think there is something that should be added to core.
