### ISSUE TITLE
Reporting - choose which type of times

### ISSUE THREAD

**Issue by kosli** [kevinpapst/kimai2#2575]
I was first puzzled with the times in the reports as I wanted to match them with the times that I see as duration (and calcualted with fixed rates). Only after looking at the https://www.kimai.org/documentation/reporting.html I saw that not all reports are using the same times -> it would be great if a hint would be shown on the specific report page.

It would be great if the type of time used in the reports could be defined by the user (either via preferences or right in the report itself). 

Why I am looking for these type of reports/times: I have written an API integration with an online accounting system that I use. I have no way to compare the reported times & rate per month (and customer/project/activity) with what I have invoiced via the API. (FYI, I do NOT use the invoices of Kimai as I need to have the invoices in the accounting system.

**Comment by kevinpapst** [comment]
Thank you @kosli for raising this topic 👍

This is a very important topic and I am currently considering to drop the `Real times` calculation entirely.

I can only remember vaguely why it was introduced originally. I think it had to do with the daily working times view on the dashboard, where entries longer than 24 hours looked weird, because it looked as if one person could work more than 24 hours a day. 
Some people might use entries like this to enter holidays, but then I think these are simply invalid bookings.

**Comment by kevinpapst** [comment]
This was changed with 1.15 - there is no difference any more. The only difference is still in the dashboard widget, where entries are split at midnight. This is a left-over and will be changed as well soon.
