### ISSUE TITLE
Poor workflow: Creating new projects & belonging teams

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2579]
After creating a new projct the input windows closes when saving it.
Now you have to search or scroll to the new project
Open the the new project
Create the team for the project
Very complicatet!

**Describe the solution you'd like**
Append the team creating to the first step creating a project (same windows)
or
When creating a project a new button helps: SAVE & CREATE TEAM for saving the new project and directly open the window to assign a team.

Same idea like in expenesesbundle  #53  for expenses in booking form to improve workflow!

**Comment by kevinpapst** [comment]
In v2 #2902 the detail page opens after creating a new customer/project/activity and you can directly create a team with one more click, so I would say this issue is (mostly) fixed.

Don't agree? 
Open a new feature request for default team behavior upon item creation e.g. assign a "Admin Team" or even a new team when a project is created.

**Comment by HeinzWuert** [comment]
in combination with a (planed) default team automatic assigned great!
