### ISSUE TITLE
RTL adjustment required

### ISSUE THREAD

**Issue by yarons** [kevinpapst/kimai2#2668]
**Describe the bug**
When switching the language to Hebrew/Arabic the interface remains in LTR (The menu is on the left for example and the arrows are pointing to the right instead of to the left).

**To Reproduce**
1. Switch the interface langauge to either Hebrew or Arabic

**Walkaround**
Manually editing the CSS and changing all the values, the problem is there are many of these changes so merely adding `direction: rtl` to the `html` tag has some effect but it's not good enough.

Maybe @eransurg can also shed some light here.

**Comment by kevinpapst** [comment]
Yes and I am sorry for that. I already invested quite some time to make Kimai compatible with Arabic and Hebrew characters. 
But making it RTL seems impossible to me. Once because the theme does not really support it and second because I have no experience whatsoever with that topic. I would love to support it and I am sorry for having that barrier in the software, but I don't know how to solve it.

There are people who worked on RTL for the used theme in the past, eg here: https://github.com/mmdsharifi/AdminLTE-RTL
But I don't know if it is possible to integrate their changes.

If you want to start working on out, I will help you the best I can (or anyone else reading this).

**Comment by kevinpapst** [comment]
Next major release will have proper RTL support. You can follow the development here at https://github.com/kevinpapst/kimai2/pull/2902

**Comment by kevinpapst** [comment]
I am closing this, because it is available in the version which will be released as 2.0 in the future.

If you want to help testing and provide feedback, please follow the issue https://github.com/kevinpapst/kimai2/pull/2902.

The changes can be tested at https://demo-branch.kimai.org with the demo logins (e.g. `susan_super` and `kitten`).
