### ISSUE TITLE
Markdown checkboxes does not render

### ISSUE THREAD

**Issue by pc-h353** [kevinpapst/kimai2#2670]
Standard markdown checkboxes (below) are not rendered at all. The chceckbox: "Erlaube Markdown-Formatierungen in Beschreibungen und Kommentaren" was checked. Other markdown elements render works fine.

Examples:
```- [ ]``` should render:
 <li> - [ ] </li>
<br>

```- [x]``` should render:
<li> - [x] </li>
<br>	

OS: Windows Version 10.0.19043
Kimai: 1.14.1 stable (Ayumi)
Browser: 
- Google Chrome Version 91.0.4472.124 (Offizieller Build) (64-Bit)
- Mozilla Firefox 89.0.2 (64-bit)

**Comment by kevinpapst** [comment]
Hi @pc-h353 😄 
Thanks for posting your first issue in Kimai! 
Yes, missing checkbox support is known and will very likely not be added (not only because it is not part of the GFM spec). 
Even if the [library that is used to render markdown](https://github.com/erusev/parsedown) would support it, I would deactivate it in Kimai. The next request would be "I want to be able to click the checkbox".

Having form elements inside user content could also become an issue with the Javascript that doesn't expect them.

I just don't see that feature in Kimai yet, thats why I am closing your request. The markdown support was always meant to be limited to some inline (or parargraph) formatting rules. 

But anyways, I like good ideas, so please let me know if you have more ideas!

**Comment by pc-h353** [comment]
Hi.

Thank you for quick reaction. Although I am little bit dissapointed I understand the reasons you've meant. I have already found another solution, so it is not the issue for me anymore.

And thank you for the Kimai, I am using it every day, so if some idea come to mind, I will let you know 😏
