### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#2706]
while updating, I get the following error message
```
[notice] Migrating up to DoctrineMigrations\Version20210802174320
[error] Migration DoctrineMigrations\Version20210802174320 failed during Execution. Error: "There exists no foreign key with the name 'fk_3beddc7f8f7de5d7' on table 'kimai2_teams'."
 [ERROR] There exists no foreign key with the name 'fk_3beddc7f8f7de5d7' on     
         table 'kimai2_teams'. 
```
any idea how to solve?

**Comment by kevinpapst** [comment]
Please share the output of 
```
SHOW CREATE TABLE kimai2_teams;
```

**Comment by BeckeBauer** [comment]
I am probably not using the right tool:
```
/web/kimai$ SHOW CREATE TABLE kimai2_teams
-ash: line 35: SHOW: command not found
```
I could manually log into the database (via phpMyAdmin) - would that be the right program where to run the `show` command?

**Comment by kevinpapst** [comment]
Sorry, yes that is an SQL command. I need to see the current structure of your table. phpyAdmin should work I guess.
I believe it is somehow wrong, why ever. 
I compared it with multiple installations and they all have this foreign key, lets see how it looks in your installation.

**Comment by BeckeBauer** [comment]
got this result:
```
127.0.0.1/kimai/		https://php.local/index.php?route=/database/structure&server=1&db=kimai
Ihr SQL-Befehl wurde erfolgreich ausgeführt.

SHOW CREATE TABLE kimai2_teams

kimai2_teams	CREATE TABLE `kimai2_teams` (
  `id` int(11) NOT N...	
```

**Comment by kevinpapst** [comment]
where is the missing part?

**Comment by BeckeBauer** [comment]
sorry, just now I managed to get the full text shown... 

```
kimai2_teams	CREATE TABLE `kimai2_teams` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teamlead_id` int(11) NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `color` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_3BEDDC7F5E237E06` (`name`),
  KEY `IDX_3BEDDC7F8F7DE5D7` (`teamlead_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci	

```

**Comment by kevinpapst** [comment]
Wow, that is really strange. From a database perspective the foreign key is missing. Normally the database makes sure that teamlead_id really holds an existing user id. With this setup you have, the field could contain invalid data.
No idea why it is missing, because it is clearly created with the exact name since teams were introduced in 2019: 
https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20190730123324.php#L37

No clue how that can happen. I will include a workaround if other users have the same issue.  

You could now edit this file and remove the highlighted line:
https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20210802174320.php#L30
Then run the updater again.

**Comment by kevinpapst** [comment]
And btw: thanks for early testing and feedback before the official release! 👍

**Comment by BeckeBauer** [comment]
Yes, after deleting this line, the update worked. Thanks for the help 👍
