### ISSUE TITLE
configurable csv/xlsx export, like in invoice. But not limited by customer/project

### ISSUE THREAD

**Issue by Martin-Forster** [kevinpapst/kimai2#2755]
**Describe the solution you'd like**
Regular export of the timesheet data to the existing erp system. Including reference information from customer and project .

**Describe alternatives you've considered**
Using the invoices function i can generated fitting lists, but they are limited to a specific customer and project.
Access to custom fields from the plugin would also be required.

Customer because it is a requirement of the invoice feature. 
Project because i need the project.order_number as reference.

**Suggestion**
Creating the title line of the 2 dimensional export table, to define the included fields. 
The invoice documentation has already extensive list of available fields.

** Duplicate
this is somehow a duplicate of #2713 
I completely forgot about that. Sorry.

**Comment by kevinpapst** [comment]
You are right this is a duplicate.
And I still don't know what you need. 
You can create your own export template and you can even create your own export mode that directly talks to your ERP.
I am closing here, because I think that everything you need is already there.
Everything else can be discussed in #2713
