### ISSUE TITLE
Context Menu on the Calendar

### ISSUE THREAD

**Issue by urinal-cake** [kevinpapst/kimai2#2914]
**Is your feature request related to a problem? Please describe.**
The problem is that when some of our employees need to put as many of their time entries that they track in other areas into Kimai, they cannot easily do it with the Calendar view.

**Describe the solution you'd like**
Being able to click the Entry on the Calendar View, and have a small context menu show up that states "View Entry/Edit" (Current functionality) as well as "Create Copy" or any of the other context menu controls that exist on the Timesheet page as part of the actions button, xpath search while in Chrome: //td[contains(@class, 'actions')]

Obviously the hover should still appear, which is super helpful. But when clicking, instead of showing the Edit Record modal, a context menu would be great (see screenshot)

**Describe alternatives you've considered**
There are no alternatives that we can find that allow for this level of functionality on the Calendar page. 

**Screenshot**
![image](https://user-images.githubusercontent.com/7855304/140570367-b40ced26-c668-4228-8886-40339a753275.png)

**Comment by kevinpapst** [comment]
Yeah, that is (believe it or not) rather complicated, otherwise it would be already there. 
The necessary permission checks make it a entry-by.entry decision what should be displayed. Given the highly dynamic nature of the calendar, I would have to load the context menu from remote. 

There are more issues regarding the calendar which at least of them cover topics with the same problem:
 https://github.com/kevinpapst/kimai2/labels/calendar

**Comment by urinal-cake** [comment]
Understood. Obviously, something as visual as the calendar has _a lot_ going on at once. If this is something that can be achieved, it would be a pretty big boon for us. Thank you!

**Comment by kevinpapst** [comment]
Next major release #2902 will finally bring the context menu to every calendar entry.
Test feedback is appreciated (see links in PR) 😄
