### ISSUE TITLE
Allow negative fixed amounts

### ISSUE THREAD

**Issue by praul** [kevinpapst/kimai2#3008]
**Is your feature request related to a problem? Please describe.**
Often, customers have credit with me. In order to bill this correctly, it would be easy to add entries with negative fixed amounts

**Describe the solution you'd like**
Allow negative fixed amounts when adding an entry

**Describe alternatives you've considered**
Budget only shows, but does not affect billing or sums

**Comment by StefanGebhardt** [comment]
Same for me. It would be very helpful that I can book negative amounts or a rebboking between two prjects (Example: User booked in project A, but clients wants to pay it with project B - so I could rebbok x hours from project A to B)

**Comment by Cata-ExF** [comment]
Negative invoices are used everywhere, it's a way to properly manage a refund to client in the accounting system.
As an example, if I issue an Invoice for an advance payment for 10 hours (which is also a common scenario), then I use the time tracker and record 15 hours in 5 separate time entries, the final invoice should be for the 5 hours, I can't send to client another invoice for 15 hours, without refunding the initial amount for 10 hours.
It's not easy to go through all time entries and calculate which ones should not be billed, will never fit exactly the advance payment, one entry will need to be manually split into 2 entries.
Therefore, a negative entry in the final invoice is needed to deduct 10 hours or a fixed amount from the tracked time.

Negative entries in an Invoice are common, for example if one needs to offer a discount to a client they add a manual item in the invoice with a negative value, the invoice total amount to be paid will reflect the discount. paypal invoicing allows negative entries, primaERP time tracker also allows manual entries in the final invoice, so I guess it's not an exceptional case.

It will be great if sometimes in the future manual invoice entries (positive or negative) will be possible.
Thank you for your work, you are doing a great job!
Catalin

**Comment by Sarmingsteiner** [comment]
We would also highly appreciate the possibility of entering negative fixed amounts. We often deal with discounts and have to deduct prepayments - this would make it much easier.

Now, we have to edit and calculate such invoices manually – a cumbersome and error-prone situation!

**Comment by Medius7** [comment]
Receiving advance payments or payments on account is a common thing.
I really hope that Kimai will offer this feature soon.

Does anyone know of a workaround by then?

**Comment by BeckeBauer** [comment]
My workaround: change the invoice amount in the database manually

**Comment by kevinpapst** [comment]
So many users want a feature: what about throwing some money on the problem together? Might speed thing up...

**Comment by Sarmingsteiner** [comment]
@kevinpapst: What sum do you think of for coding a quick solution - just allowing negative fixed amounts?

**Comment by kevinpapst** [comment]
I will definitely NOT allow negative amounts in timesheets.

What I think are viable solutions: 
- allowing to put a balance on a customer (step 1)
- allowing to set a budget on a project (step 1)
- allowing to create expenses with a negative amounts (maybe)

**Comment by Sarmingsteiner** [comment]
@kevinpapst: How about coding a "special version" for @praul and @Sarmingsteiner , and tell us which files needs change for future updates?

**Comment by kevinpapst** [comment]
How about: this is open source, you can click fork and do it yourself 👍

**Comment by Sarmingsteiner** [comment]
@kevinpapst I would if I could. OK, so we can't hire you as a developer, and have to look for another PHP/TWIG developer?

**Comment by kevinpapst** [comment]
Sure you can hire me. But not for a feature that I reject and that could break things now or in the future. 

Instead of becoming off-topic we could discuss my ideas. If you don't like any of them, we could discuss that too.

**Comment by Sarmingsteiner** [comment]
So, do you mean your proposals like this?

"allowing to put a **(negative)** balance on a customer (step 1)
allowing to set a **(negative)**  budget on a project (step 1)"

**Comment by Medius7** [comment]
Having a "positive/negative balance" / credit on a customer would be an elegant solution :-)
Of course, this credit should then be offset against the next invoice.

**Comment by kevinpapst** [comment]
Ops, above I meant "Putting a **balance** (not **budget**) on a project".

I am mainly a software developer, definitely not a finance expert. What I mean is: a customer paid 1500 in advance then he has a balance (or credit?) of 1500. The next invoices would then be reduced up to a total of 1500.

Allowing the opposite doesn't make sense to me, because you can achieve the same already with expenses, which show up as invoice items.

**Comment by BeckeBauer** [comment]
One more idea: allow a third option in addition to pending invoice and paid invoice namely an entry for a partial payment. Then, the invoice (and timesheet) remains unchanged and the negative amount is just a calculation figure for the amount open for playment (I hope I am not off topic but that is what I understand as negative amount - and what also be needed since clients sometimes pay in instalments)

**Comment by Sarmingsteiner** [comment]
Finally! I could find and change the relevant pieces of code for the quick and - obviously - very dirty approach to allowing negative fixed amounts.
Invoice calculation seems to work fine.
Disclaimer: Since I am not a software developer, I did no proper testing.

@kevinpapst : Do you feel comfortable with publishing it?

**Comment by praul** [comment]
@kevinpapst : Putting a balance on a project sounds nice and could work for these scenarios.
It would need to be automatically cleared /marked as exported though, once an invoice generated. 
I would greatly look forward to this, thanks a lot (also for all your work, I love kimai).

@Sarmingsteiner: Could you point me to the file. I was looking for it, but gave up. I would like to give this a try too. Thanks!

**Comment by kevinpapst** [comment]
@Sarmingsteiner If it fixes your urgent needs: great! Go ahead, this is open source and I do embrace discussions about code. I am just not going to join the discussion on this one. And be warned: fixed amounts are already planned to be removed from the next major version, so you might end up riding a dead horse here instead of helping me to implement it properly.

And everyone: as soon as you patch files, please don't post questions here if the next updates fails... or if something doesn't work as expected.

**Comment by praul** [comment]
@kevinpapst : That's unfortunate, but thanks for the info. I use this feature quite a lot, because sometimes I have fixed amounts for certain jobs in my contracts and I still want to track the time for this. I suppose I could stay on legacy version though. Please mention this in the changelog then, so I can avoid accedentally upgrading.
Sorry for the offtopic.

**Comment by kevinpapst** [comment]
You can still create an entry with one hour and set the hourly rate to the (previously fixed) amount, if using expenses is a no-go for you...

**Comment by praul** [comment]
Awesome. It's about time I spent some money on kimai and this will make my life a lot easier!

**Comment by kevinpapst** [comment]
The [last version of the expenses plugin](https://www.kimai.org/store/expenses-bundle.html) supports negative amounts.
You can test it in the "Plugin demo" - see https://www.kimai.org/demo/

**Comment by kevinpapst** [comment]
I am closing this issue now, as I am not going to support negative fixed amounts.
All the pother mentioned points can be discussed in new issues or already created discussions.

**Comment by kevinpapst** [comment]
BTW: if you have ideas how to improve the invoice system, please open up issue. Write those issues as abstract ideas and try to think free, without relying on existing code. 
If you think there should be other solutions to improve invoices, eg. handle negative invoice items differntly, add skonto, balances ... go ahead and open new issues.
