### ISSUE TITLE
GPS support for mobile devices?

### ISSUE THREAD

**Issue by deknos** [kevinpapst/kimai2#3355]
**Is your feature request related to a problem? Please describe.**
Hello,
i want that my colleagues, if they consent that their apps/devices can be tracked via gps and that i can check that

**Describe the solution you'd like**
i wanted to ask if it is possible to add low-energy gps location to the smartphone apps and this is stored in the server and at least exportable, if not showable with e.g. openstreetmap at the serverbackend for the user and/or the HR person

**Describe alternatives you've considered**
There's no alternative, as i want that the time and gps location with the timetracking/punch feature clock is connected. when they start driving to work and punch in in the app, i want that their way to their workplace this day is also calculated as worktime, if i want that.

**Comment by kevinpapst** [comment]
The mobile apps are not developed by myself, so I cannot talk about those.

But I will not add GPS tracking to Kimai core.
Not only is that illegal in some countries, automatic tracking is also highly disrespectful to your employees.

I might add a custom GPS tracking field to the custom fields plugin though, whose functionality can be turned on and off by the user himself. Its already more than I like, but I do understand that there are valid use-cases.

I am closing this, due to the explained reasons above.
If you still want it: contact me via email for extending the plugin as paid contract.
