### ISSUE TITLE
Freeze / Float permission table column labels

### ISSUE THREAD

**Issue by skadarnold** [kevinpapst/kimai2#3357]
When editing permissions table in the Role settings, it is difficult to easily retain in memory the columns that you are working with when scrolling down through several permissions. 

It would be nice if the very first row of the table where the role labels are listed was frozen in place so it does not scroll with the rest of the permissions. That way you always have a visible reference of what column you are editing.

**Comment by kevinpapst** [comment]
I am closing this, because it is available in the version which will be released as 2.0 in the future.

If you want to help testing and provide feedback, please follow the issue https://github.com/kevinpapst/kimai2/pull/2902.

The changes can be tested at https://demo-branch.kimai.org with the demo logins (e.g. `susan_super` and `kitten`).

**Comment by skadarnold** [comment]
This is excellent. Thank you for making me aware of upcoming 2.0 and its progress. Its looking really good. I have been using kimai for a few years with 50 - 100 active users on average. It has been great so I am happy to see it evolving . I will try to contribute where I can.
