### ISSUE TITLE
Confirm edit dialogs with keyboard shortcut

### ISSUE THREAD

**Issue by j2L4e** [kevinpapst/kimai2#3572]
When I create or edit entries I frequently find myself pressing ctrl+enter after entering the discription (expecting the dialog to save and close). Clicking the button or tabbing all the way down is the only way to save it, though.

A keyboard shortcut to trigger a dialog's non-cancel action would be nice. I find ctrl+enter convenient, but that's just my preference.

I'm up for a PR if this is a feature others would like to see as well.

**Comment by kevinpapst** [comment]
I just added keyboard shortcuts in the last release and improving them is very welcome:
https://www.kimai.org/documentation/keyboard-shortcuts.html

I could imagine that you cover > 90% of all use-cases with adjusting these two locations:
https://github.com/kevinpapst/kimai2/blob/master/templates/default/_form.html.twig#L24
https://github.com/kevinpapst/kimai2/blob/master/templates/default/_form_modal.html.twig#L32
We still need to search for the block name `submit_button `, not sure if it is overriden somewhere.

CTRL+ENTER does not sound like an accesskey that is available by default. I would prefer a standard way for keyboard shortcuts, instead of listening to javascript events.

**Comment by kevinpapst** [comment]
I understand the wish for the platform specific submit combination. 
I think on Mac I would expect command instead of control.

But please give accesskey a try first and if it does not work, you want to have a look into the Modal-Code:
https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiAjaxModalForm.js
Maybe you can hook in there somehow.

**Comment by j2L4e** [comment]
May I ask, why you prefer accesskey over a more versatile JS solution like https://github.com/ccampbell/mousetrap?
Is it because of pure server-side implementation? Having different hotkeys per OS / browser seems like a serious drawback to me.

**Comment by kevinpapst** [comment]
4.5kb of Javascript for a keyboard shortcut and licensed under the Apache License. Neh.

I can tell you right away that 99% of all users do not care about keyboard shortcuts and I don't like (javascript) dependencies.

**Comment by j2L4e** [comment]
How about this? https://github.com/kevinpapst/kimai2/commit/afd21917ea027553916f41c50f6ac0b6581d752d

Easy to implement server-side and consistent across browsers, works beyond a-z characters. Ignores invisible elements. Works with injected html, too. The data-hotkey attribute is arbitrary. It could be `data-hotkey=foo` as long as it's consistent.

I tried out accesskey and it obviously works in a way. But there wasn't any meaningful key to assign. "s" is already used to stop the clock and I couldn't think of another letter to use for a save or submit button.

**Comment by j2L4e** [comment]
> do you have an idea now for more actions
Can't say that I have. I removed the loop.

**Comment by kevinpapst** [comment]
Tried, works awesome. Thank you so much for the PR @j2L4e 👍 

Beta release coming soon!
