### ISSUE TITLE
for new V2: Custom Fields

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#3601]
### Describe the problem

new function offers tags and colors.
Unfortunately you are using the old color selection box and not the new user defined color palette in the settings.

When listing projects the filter function is poor, works only with the customer field and not with custom fields.

Custom fields are still not sortable.

Everything else looks good!

### Describe the solution you'd like

xxx

**Comment by kevinpapst** [comment]
> Unfortunately you are using the old color selection box and not the new user defined color palette in the settings.

I added the choice between free and user defined values (demo not yet reinstalled).
<img width="256" alt="Bildschirmfoto 2022-10-26 um 16 04 09" src="https://user-images.githubusercontent.com/533162/198047532-8d621743-8cc0-467c-bb4b-421ca2335a04.png">

> When listing projects the filter function is poor, works only with the customer field and not with custom fields.

???

> Custom fields are still not sortable.

And that will very likely not change due to technical limitations.

**Comment by HeinzWuert** [comment]
Thanks, so this item may be closed
