### ISSUE TITLE
setup for Synology or STRATO

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#469]
Anybody with more infos since the last trial?

Is an installation on Strato Webspace with MariaDB possible? (not Strato server!)

**Comment by hmr-it-jr** [comment]
Kimai2 works perfectly on shared web hosting servers of netcup. So chances are high that it will work on shared hosting servers of strato, too.

**Comment by kevinpapst** [comment]
@hmr-it-jr I guess the problem is, that there is no proper documentation on how to install it in a shared web hosting environment. I am using root server since more than 10 years, so I cannot share insights how to install Kimai and which problems might arise.

There are FTP installation steps available, but I wrote them down without testing, so if you have any input how Kimai can be installed or how the documentation can be improved, please let me know and I would happily add it to the docs!

**Comment by hmr-it-jr** [comment]
@kevinpapst I followed the exact steps of your guide and it worked perfectly. The only thing I had to adjust was this:
![grafik](https://user-images.githubusercontent.com/36242595/52900414-b9796500-31f5-11e9-9e3c-3e78248c5081.png)

but I don't know if this has to be set on other webhosting providers.

**Comment by kevinpapst** [comment]
Please see this issue #642 which adds a FTP package. 
There is a package for the upcoming version 0.9 linked which can be used for FTP installation.
I need feedback from FTP users, as I cannot test it properly.

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/synology.html
