### ISSUE TITLE
Sub-projects and sub-activities

### ISSUE THREAD

**Issue by subdiff** [kevinpapst/kimai2#484]
A hierarchical structure often comes natural to tasks and/or projects. Would it be possible to add this as a feature, such that one can assign parent projects/activities to projects/activities?

Showing the sub-projects/activities in the list of all projects/activities below the parent project/activity would be a first user-facing improvement. Then maybe it could also be possible to show hours, income etc. for child and aggregated for parent project/activity.

**Comment by rarvin** [comment]
Dear @kevin could you please add a sub activity so that it is customer-->project-->activity-->Sub-activity (and make the subactivity global as well as specific to an activity). Similarly this must be filterable in all reports/timesheet/invoice etc. Could you please do that. We are really in need of this feature. Even if it is released as a plugin we are ready to buy. So in the overall hierarchal structure one would need to bring in one more level called subactivity. If you would like you have this restricted through setting so that only users would would like this additional level may enable it.

**Comment by rarvin** [comment]
@kevinpapst Dear Kevin with the implementation of verticals forms allowing you to add more drill downs etc easily could you please see if you can implement a sub-activity for an activity. We now have lots of subactivities which are listed as entries under activities which are not really needed for all users just specific to few activities but since subactivites is not present we are forced to have them listed an an entry under activities. 

An example is an article could be single column or double column and work done for each is differ, this doubles the number of activities to twice the number. We can’t have this as a global activity since not all activities are having double column or single column type of activities. Having sub activities can really simplify the overall scheme for us as well as this can help other Kimai users to to have a much more sleek hierarchical structure. 

I hope you would consider this request.

**Comment by Bjoern3003** [comment]
Would be very nice, maybe also to check the child activities, if they are completed (with log to see who has checked this entry).

**Comment by rarvin** [comment]
@kevinpapst is there any way you can provide sub-activities. It would be really helpful. If standard users do not want this sub-activiites you could create an enable flag from system activities to enable disable it and only users who really want it could have it enabled. Can you release this as a plugin if needed.

**Comment by kevinpapst** [comment]
This is an old topic and I already said it in the past: sub-activities / sub-projects will not be added.
Sorry. I know that some users might need it, but I will concentrate on improving what is already there / planned for the future.
