### ISSUE TITLE
Export timesheet only exports entries on the current page

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#534]
**Describe the bug**
On My times -> Export timesheet, it only exports entries on the current page, not everything 

**To Reproduce**
1. Go to 'My times'
2. Make sure there is more entries than the page size (default:25). Pagination available at the bottom.
3. Click on 'Export Timesheet' on the top right corner.
4. On the new window it shows only the visible records from the first page, not all of them. Total is calculated only for these entries.

**Expected behavior**
I think it should export all filtered records, not just the visible ones from the first page. Page size cannot be greater than 100, so I cannot calculate totals for more than 100 entries with one click. 

**Additional context**
It works this way in the demo installation.

I could use invoices for this, but I use this because I just need quick summaries for custom projects and timeframes, and I found I can calculate custom totals quicker this way than with invoices. 

Adding an 'unlimited' option to page size would solve this issue temporarily.

**Comment by kevinpapst** [comment]
I don't want to support unlimited items for the regular user, neither in the export nor on the "My Times" page. This could be a potential problem, as showing unlimited items might kill your PHP process or your browser due to resource limitations (such as RAM).
When you choose no filter, this means => showing all ("unlimited") items, but paged.
One option would be to show the export button only if a filter was chosen, but that would be a bad UX, as its not clear that (initially invisible) filters are somehow connected to the export button.
Its easy to add more choices for the page size, but my tests with live data showed, that this should not be increased to much. So where do you make a cut? Should that be a config option?

And we should talk about the use case behind this button and my intention was:
"giving the user the option to pass his monthly timesheet to his boss"

The "simple user timesheet export" was never meant to be a source for what you seems to use it for.

If you are running your own Kimai instance, you probably just want to wait for the export module (very soon available - already in work), which does all you want in a much better way.

**Comment by infeeeee** [comment]
Ok, thank you I'm waiting for the exports, that's what I really want!

**Comment by kevinpapst** [comment]
Even though the export module will add a lot of the missing pieces, it won't be available to the regular user in a larger installation, so the user-export needs to be improved.
I'd like to collect some good ideas how that could be achieved. Please share them!
- A simple one is to use a configuration for the max amount of allowed items per page
- Another one is to not limited the exported items to the page size, but instead for the user to select a time-range (to avoid creating exports for his entire history)

**Comment by bydecker** [comment]
From a UX perspective it makes sense to take the time-range into account while exporting and ignore the paging. I don't see a use case for exporting a report limited to a fixed set of records. 

So my suggestion would be to export all items according to the filter parameters. If those items exceed a certain amount (that could potentially cause PHP/memory issues), you could warn the user about that fact instead of forcing the limit.

**Comment by infeeeee** [comment]
Ideas: 
- calculate subtotals. On a dropdown the user can select if they want subtotals by customer, by project or by activity. Maybe an option for export only totals and subtotals without individual entries. Maybe subtotal by month, by day, by week as well. 
- Not exactly about the export but I think it's connected to this issue: I liked the quick buttons in Kimai 1, where I could quickly select last month,this month, last week, this week etc. It would be nice if they reappear.

**Comment by kevinpapst** [comment]
@bydecker the biggest problem is: the default filter shows all records. So every time someone hits the  export button, the complete history would be exported. This is less than sub-optimal.

@infeeeee new feature request => new issue, otherwise this will get lost.

I could use your help in #538 with testing and feedback.

**Comment by bydecker** [comment]
Ah, I see the problem, but if I hit export without any filters, it only shows me the current month. That should still be a manageable amount, shouldn't it?

**Comment by kevinpapst** [comment]
Lets shortcut this discussion, your points are totally valid, so I fixed the issue: all records for the selected time range will be included.
If no range ist, the items for the current month are exported.
