### ISSUE TITLE
Sorting in various tables/pages like User, Customer, Project & Activities

### ISSUE THREAD

**Issue by jaapcrezee** [kevinpapst/kimai2#543]
**Describe the solution you'd like**
Make the columns sorteable on those pages. For example by clicking on the 'name' column to get it sorted asc. or desc.

**Comment by Creanimo** [comment]
Yes, this would be amazing. My activity list is long and jumping back and forth a lot from activities that should be next to each other. Sorting it by name would be so helpful.

**Comment by kevinpapst** [comment]
Not that it deny the topic of the feature request, but they are sorted by name ;-)

**Comment by Creanimo** [comment]
It's super helpful that they appear alphabetically in the Dropdown. But the lists in Administration > Projects or Administration > Activities don't (at least in my Kimai v2 - 0.8.1 stable from Yunohost). I created already existing activities a couple of times now, because I looove being very detailed with sub-activities and didn't see them in my list because they were all over the place.

It might also be helpful to sort (or even group them under a summary column) by activities alphabetically in "Export" to quickly see how much time was spent on a certain activity in total.

**Comment by kevinpapst** [comment]
You should always check the demo for already existing features: http://www.kimai.org/demo/ 
You are using a version which is a couple of month old.

The second point should be a new feature request, unless the [new budget reporting](https://github.com/kevinpapst/kimai2/pull/843) (check demo) is not sufficient.

**Comment by Creanimo** [comment]
Ah, great to know that alphabetic sorting is the default now. But the original feature request is still valid, right? Although the filter option is already a great way to segment the list and most fields can be filtered for. 🤔
That budget reporting function looks very useful!

**Comment by bjoerne2** [comment]
Default sorting of activities should be by date (or DB id) in descending order. Then you have quick access to the newest activities. That would be helpful immediately after creating an activity when you want to start tracking.

Currently my workflow is either

Create activity, search activity in list of > 1000, context menu "Create timesheet"

or

Create activity, memorise name which often starts with a technical issue id, go to Timesheets, create entry, select project, remember activity name

Both are not very comfortable. With a different order it would be

Create activity, find the activity as first entry, context menu "Create timesheet". Done!

@kevinpapst What do you think?

**Comment by kevinpapst** [comment]
You have no idea, how many people asked for alphabetical ordering.... ;-)
I know that sorting is needed it and its definitely on my roadmap for on of the next releases.

But I wonder: 
- Why are you starting a new record via the activities screen?
- Why do you have 1000 visible activities? 

In my workflow I have 5 global activities and in some projects a handful of project-related activities. What is the reason behind having so many activities?

**Comment by bjoerne2** [comment]
I start a new record from the activity screen because that's the point where I am after creating an activity. Usually I already want to track some time when I'm there.

I have so many activities because many activities correspond to issues from issues trackers. That last from from small bugfixes (15 minutes) to bigger topics (several days). All activities are project based.

You mentioned the word "visible". I could make older activities invisible, I guess. But with the big amount of activities that's something I don't want to do manually.

**Comment by kevinpapst** [comment]
Visibility is inherited from customer to project to activity. But thats only feasible if some of the projects or customers are not used any longer. Give it a try...
Back to topic: sorting by creation date will be one of the possible filters then.

**Comment by relume** [comment]
Kimai2 v1.1

User selectable sorting of different table information would be very helpful. 

- For our use (our project names have an ID prefix like PR2019.010, PR2019.011 ...) it would be most helpful, if projects could have reverse (alpha) sorting (by admin default). 
- Thus newest projects appear on top not only in the project view but also in the time sheet selector.
- Actually it is some bit annoying, entering new projects and there after we have to navigate again and again to the last paste to see the new entry.

Many thanks for any (near time) consideration.

**Comment by kevinpapst** [comment]
I worked on table ordering for 1.2. 
See #1086
Demo installation existing. Please test it and leave your feedback.

**Comment by relume** [comment]
Thank you very much. Works perfect.
