### ISSUE TITLE
SSO using Kerberos

### ISSUE THREAD

**Issue by Gregger83** [kevinpapst/kimai2#557]
It would be nice to be able to configure SingleSignOn using Kerberos.

**Comment by h3ge** [comment]
I am currently trying to implement SSO using the headers set by apache like I did it with kimai v1 (Apache handles my kerberos authentication because I never trust an application)

But I'm struggling a lot with the framework, can someone give me a hint where the authentication currently is  taking place and where I can inject my custom code, so I can check if the user has already been authenticated by apache?

**Comment by kevinpapst** [comment]
I have no clue honestly as I never tried it myself. All I can provide is a link to give you a first starting point:
https://symfony.com/doc/3.1/security/pre_authenticated.html#remote-user-based-authentication

**Comment by kevinpapst** [comment]
I will work on that if a company will pay the implementation.
Closing for now, as nobody voted.
