### ISSUE TITLE
Export permissions in local.yaml

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#561]
Hi Kevin,

for users with role „ROLE_USER“ i set the permission in local.yaml to

`view_export,create_export,edit_export_own_timesheet`

and with that configuration a user can select/export the entries of all users.

**Comment by kevinpapst** [comment]
Is there any question?

**Comment by blochwitz** [comment]
The question is: how can i set the permissions in a way that a user can only export his own timesheet. It seems that the permission `edit_export_own_timesheet` doesn't work...

**Comment by kevinpapst** [comment]
There are several options in Kimai to export data, please be clear with your issue description.
Now I have to guess what your question is and that  is frustrating, because I might be wrong with my assumption.

Did you read the documentation?

https://github.com/kevinpapst/kimai2/blob/master/var/docs/permissions.md#existing-permissions
> edit_export_own_timesheet - set the export state of your own timesheet record

What exactly is not working? You expect that this permission does something else than it is supposed to do.

https://github.com/kevinpapst/kimai2/blob/master/var/docs/export.md#security-and-privacy
> Giving a user the permission to export data allows to basically see everything inside Kimai. So all customer, projects, activities, all hourly rates, the personal time worked, the money earned become visible!

Normal users don't have access to the export module for a reason. They have their "small export" in the timesheet view.

**Comment by blochwitz** [comment]
Okay i understand. So users should only use the „small export“ module...

**Comment by kevinpapst** [comment]
Yes, the new export module does not take many permissions into account. It allows to see and dump all available data, therefor it should only be visible to certain users.
If you want/need some of the features in the "small export", please open a new issue for it.
