### ISSUE TITLE
Store filters between requests

### ISSUE THREAD

**Issue by DERanselmus** [kevinpapst/kimai2#564]
Hi.

using one of the "Actions" in "My times" resets the Time range filter. Is this intentionally? If yes, a flag preserving the filter settings would be useful.

Chees
Stephan

**Comment by kevinpapst** [comment]
@DERanselmus is this still an issue for you with all the changes that were applied in the last time (e.g. the modals, not leaving the list view)?

**Comment by StefanWinterberger** [comment]
Upvote:
Feedback from a User: At least the Page Size and the TimeRange should be persistent. (I would say in the scope of the active session). Even better would be, if all filters are persistent and an additional clear filter button. (And a marker if filters are active or not.)

**Comment by kevinpapst** [comment]
@StefanWinterberger please use the "thumbs up" reaction on the initial post. This way I can filter the issues.

**Comment by Aybee** [comment]
Retated 
https://github.com/kevinpapst/kimai2/issues/1752
UX: Filter/Search values handover? save to session or user profile?

**Comment by labor4** [comment]
> @DERanselmus is this still an issue for you with all the changes that were applied in the last time (e.g. the modals, not leaving the list view)?

Hi Kevin and everybody
I think "modal" solves this specific question. Doing this with 1.9.
But the issue at #1752 is a broader question, therefore not a duplicate.

> Related
> #1752
> UX: Filter/Search values handover? save to session or user profile?
@Aybee Did you check #1752 with a recent version?

The difference between the two issues:
This one here concerns the same-page scope that is fixed with a modal UI.
#1752 asks for storage of these values across a different page loads (for example Invoices versus MyTimes)

#1752 depends on a UX question, "why/do would we even need this", which is explained over there.

**Comment by Aybee** [comment]
To me it seems not to be a big different between this 2 issues. Both are dealing with the filter settings and that we have to set the filters over and over again.

E.g. I'm working with project X and filter to only this project. But as soon as I go to another page (choosing an action from the dropdowns also means requesting another page) and come back to my filtered page, then the filter is gone since the URL query is responsible for the filter settings. On new pages there is never a query from a previous page there are no querys at all.

**Comment by Aybee** [comment]
Test this is in Firefox with Violentmonkey or similar to get a taste of the new comfort. Fill in your matching URL first.
```js
// ==UserScript==
// @name        Kimai 1.11 stable (Ayumi)
// @namespace   Violentmonkey Scripts
// @match       https://your.timetrack.domain.de/*
// @grant       none
// @version     1.0
// @author      Aybee at Github
// @description Make the filters permanent
// ==/UserScript==

// store the query to make the filters permanent
var urlPathname      = window.location.pathname,
    urlWithoutQuery  = window.location.origin + urlPathname,
    urlQuery         = window.location.search,
    urlStoredQuery   = localStorage.getItem(urlPathname);

// reload the page with a stored query if url has no query but there is a stored query
if(!urlQuery && urlStoredQuery)
{
  window.location.href = urlWithoutQuery + urlStoredQuery;
}

// url has a query - store this new query if it differs from stored query
else if(urlQuery !== urlStoredQuery)
{
  localStorage.setItem(urlPathname, urlQuery);
}
```
Press F12 for the Devtools and see the local storage at the "Web-Speicher" tab (_"Web Store" in English? I'm German._).

**Comment by labor4** [comment]
you are right. 
they overlap/ are a subset of the other. 
Kevin reopened the other, because of the more narrow wording here. I guess for upvote reasons, one or the other needs to be closed. If this one here stays, the missing arguments may be added. the title would allow it. 

two use cases, same solution.

**Comment by Aybee** [comment]
I think the overall subject should be "Make the filter settings permanent on a per site basis" or similar.

There could be a field `session` in `kimai2_users` to store the filter settings per page. Should be saved again after clicking on the filters search button.

**Comment by Aybee** [comment]
The sorting of the tables should also be remembered per page.

**Comment by kevinpapst** [comment]
I am working on that feature right now and you can test it. See https://github.com/kevinpapst/kimai2/pull/2445

**Comment by StefanWinterberger** [comment]
Looks very good!
I am looking forward to V1.14.

**Comment by Aybee** [comment]
Hello Kevin, many thanks 💯 Have no time to test it yet but will have a look at it within the next version. I will disable my JS and test it with the modal. Will be back if I find some issues 😉
