### ISSUE TITLE
allow login of customers

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#579]
**Is your feature request related to a problem? Please describe.**
In Kimai v1 it was possible for customers to login into kimai after setting a password for them.

![grafik](https://user-images.githubusercontent.com/36242595/52952010-98df1580-3383-11e9-9adc-18d797904ee4.png)

**Describe the solution you'd like**
Create an option to set a password per customer that they can login into Kimai v2 and view their projects, timesheets of their projects and exports as it was possible in Kimai v1.

**Comment by hmr-it-jr** [comment]
So I did some testing and research.

There is a user in the demo of kimai2 called "clara_customer" which is not mentioned in the list of demo users with password that's why I haven't found it earlier.

Firstly, after login with clara_customer it's possible to record time. I think it's better to disable time recordings for customers - just give them read only access.

Secondly, I wasn't able to find out how to allocate a user (customer's user account) to a customer - i just found the option to assign the role "customer".

**Comment by kevinpapst** [comment]
Its nowhere documented, because its not supported for now.
What I remember: 
- currently every User gets the role ROLE_USER, so you can't limit the permissions down to less than that
- the role hierarchy currently defines, that ROLE_USER inherits from ROLE_CUSTOMER

You can try that by removing all roles from a user and saving => ROLE_USER won't go away.
So this is one of the places that need to be fixed.

If you want to do some more debugging: 
- try to remove the ROLE_USER in the roles column in the database table user
- create a permission map for ROLE_CUSTOMER and only assign `view_own_timesheet`

But even if that works, access to customers/projects is not limited...

**Comment by DanSman** [comment]
That's a good feature. Is it possible in version one only to see the customers projects and times? Haven't tried it yet. Thanks

**Comment by kevinpapst** [comment]
Should be achievable with teams and roles now?!?
If not, I have no intention to implement something else like this. If anything, then #629
