### ISSUE TITLE
Non visible customer/projects etc are shown in dropdowns

### ISSUE THREAD

**Issue by Mikesch-mp** [kevinpapst/kimai2#597]
If i set a customer/project etc to non visible i cant see it in the normal pages, but when i render my invoices i still see them in the dropdowns.

**To Reproduce**
1. Set Customer to non visible
2. Go to my invoices page and open the customer dropdown
3. See error

**Screenshots**
The hidden Customer:
![image](https://user-images.githubusercontent.com/6574967/53294320-c8a77680-37e4-11e9-9cac-3ba903ea15dc.png)

![image](https://user-images.githubusercontent.com/6574967/53294336-1a500100-37e5-11e9-9f08-6c257aa99bcd.png)

**Additional context**
 - Kimai version 0.7
 - PHP version 7.2

**Comment by kevinpapst** [comment]
Hm, I am still not sure what the perfect handling should look like.
It definitely shouldn't be possible to start hidden entries, but should the really disappear from all dropdowns?

Then you wouldn't be able to create invoices for them or a user wouldn't be able to find out how much they worked on these projects. Or teamleads/admins couldn't filter them.

Maybe hiding them completely is the easiest solution, but then it should still be possible to find  time records otherwise.

**Comment by Mikesch-mp** [comment]
Maybe add an option next to the dropdowns to include non visible entries or make it a configuration option either to include or exclude them. I use it for projects/customers etc. that are done or not active anymore.

**Comment by kevinpapst** [comment]
I gave it another thought: the original idea was to hide invisible items from all selects and that's also what is written on the website:

> Archiving: After a long usage a lot of entries can pile up in your dropdowns - now you can hide customers, projects and activities

The PR #628 removes invisible items. Can you help testing @Mikesch-mp ?

**Comment by Mikesch-mp** [comment]
As soon iam at home i will test it.

**Comment by Mikesch-mp** [comment]
Works perfect for me :) Thank you fpr the quick fix 👍
