### ISSUE TITLE
Creating new customers / projects / activities from timesheet form

### ISSUE THREAD

**Issue by orzechow** [kevinpapst/kimai2#621]
**Is your feature request related to a problem? Please describe.**
When creating a new time track entry it would be handy to be able to create new customers / projects / activities from the form directly.

This would shrink the time spent on creating these drastically if you're not using fancy features like customer currency, etc.

**Describe the solution you'd like**
The customers / projects / activities fields could have a plus button next to them, which changes the dropdown list to an input field:

Before click:
![auswahl_035](https://user-images.githubusercontent.com/5220714/53887572-dc43b000-4022-11e9-9dc6-7c77c0431509.png)
After click:
![auswahl_036](https://user-images.githubusercontent.com/5220714/53887593-e796db80-4022-11e9-8fde-8e4871850dad.png)

When submitting the time entry this new customers / projects / activities would be created right away (with other information like customer country, etc. on default / empty).

**Describe alternatives you've considered**
A simpler, little less effective, but still good improvement would be a plus button that redirects to the new customer / project / activity form.

**Additional context**
Using Firefox 65.0.1 on an Ubuntu-based Linux system.

**Comment by Julianoe** [comment]
Hi there!
I've been looking for an alternative to proprietary time trackers and trying Kimai this is honestly the thing that I think it is missing the most (at least for freelancer scenarios or small team). 

In some cases users don't want to spend 40 seconds filling forms about activity/project etc etc. They just want to track the time. I agree with @orzechow that the "simple" fact of allowing the creation of an activity within the time tracker would greatly improve the user process.

The heavy flow of activity creation has led to sometimes not tracking the time because I just want to dive into the activity not waste time filling form :(

Thanks anyway for you work and time

**Comment by kevinpapst** [comment]
Workaround: Create a customer/project/activity combination for "I will correct these later". You can then start the activity with 2 clicks (open action dropdown > restart record), eg from "latest activity" menu.

I do agree that it might be missing in certain scenarios, don't get me wrong!

But honestly: I never missed that feature. I am just saying that, because the important part in
> this is honestly the thing that I think it is missing the most

is the `I think` 😁 

This feature requests is totally legit and I heard it a couple of times before, so: accepted. 
But I don't feel it is important, so I will likely not work on it personally. 
But this is open source and I would accept PRs and even would help writing the code, so if someone feels inspired, please go ahead!

**Comment by Julianoe** [comment]
> Workaround: Create a customer/project/activity combination for "I will correct these later". You can then start the activity with 2 clicks (open action dropdown > restart record), eg from "latest activity" menu.

I did not think about this. Good little hack to workaround this issue for now.
I'm sure lots of freelancers would agree with me. For people managing a team that's probably not that necessary of a feature for sure.

>  But I don't feel it is important, so I will likely not work on it personally.

I totally understand, just wanted to add a contribution to the conversation. Thanks for the answer.

**Comment by XCame** [comment]
Just to underline, that some more people would love this feature. 

For our (small Team) workflow, this was the biggest drawback when switching from Kimai to Kimai2.

We have a very varying activities. 
And because of the different workflow compared to Kimai we are not using the timer function but instead we track our time by creating the activity, searching for it and then use the create timesheet function from the dropdown. 

It kind of works, because we are used to it now but in our dream Kimai it would be:

- Open Task
- Select Project
- Enter Activity (and select from dropdown if already existent)
- Start

- Stop Task
- Enter description, if needed



Instead of

- New Activity 
- Select Project
- Save Activity 
- Select Activity and create Timesheet
- Save Timesheet without entering anything to start timer

- Stop Task
- Enter description, if needed


Well... writing it down it even doesn't look as complicated to me, but knowing that others do want this feature too I still think that it would be an improvement

**Comment by UC-VR** [comment]
This feature would have been amazing! The only reason, why I switched to another time tracker.
With a small team of few freelancers, being able to quickly add Activity just to log the time would be a killer feature.
This becomes more obvious when starting a new project or working for a new client.

This would make return back to Kimai (cloud version)!
If I was a developer, I would help :(

How can I vote for this feature?

Thanks

**Comment by kevinpapst** [comment]
Next version #2902 will allow to create new activities from the dropdown:
<img width="718" alt="Bildschirmfoto 2022-08-08 um 01 06 04" src="https://user-images.githubusercontent.com/533162/183314511-44b11405-13fd-4814-a67f-951e243b543c.png">

Support for creating `customers` and `projects` will NOT be added.
