### ISSUE TITLE
Plugin page does not show installed plugins

### ISSUE THREAD

**Issue by simone-gasparini** [kevinpapst/kimai2#728]
**Describe the bug**
Plugin page does not show installed plugins

**To Reproduce**
Install the Custom CSS plugin, go to plugin page.

**Screenshots**
<img width="708" alt="Schermata 2019-04-26 alle 17 38 17" src="https://user-images.githubusercontent.com/1280258/56819532-38b89400-684a-11e9-80ef-dd32515d1b6b.png">
<img width="589" alt="Schermata 2019-04-26 alle 17 37 56" src="https://user-images.githubusercontent.com/1280258/56819540-3b1aee00-684a-11e9-8f05-f8848d611c9d.png">
<img width="590" alt="Schermata 2019-04-26 alle 17 38 00" src="https://user-images.githubusercontent.com/1280258/56819539-3b1aee00-684a-11e9-97c4-bbaa7827df61.png">

**Additional context**
 - Latest commit on 2019/04/26
 - PHP 7.3.4

**Comment by kevinpapst** [comment]
Thats not a bug, but expected behavior, see UPGRADING.md.
You need to install this branch: https://github.com/Keleo/CustomCSSBundle/tree/kimai-0.9
Hmmmm, will writing that, I guess I could merge it directly,  as the plugin feature is new in 0.9 and never released officially - yes good idea, I'll do that later on.

Oh, and thanks for posting 👍 its really good to get some help with reviews!
