### ISSUE TITLE
More actions on data records resp. table rows

### ISSUE THREAD

**Issue by bjoerne2** [kevinpapst/kimai2#748]
I'd like to have more actions for the table rows to have more ways to use the existing functionality. This request goes hand in hand with #747 (menu instead of icons) so that adding actions is possible without using more space and finding fitting icons.

Here a few actions I'd like to see:

Customer: Add project
Customer: Show records -> filter by customer
Project: Add activity
Project: Show records -> filter by project
Activity: Show records -> filter by activity
Activity: Add timesheet records
Timesheets: New record for same activity

**Comment by kevinpapst** [comment]
Based on the PR #746 do you want to help and add them?

Most of the tasks should be very simple to achieve by adding the route actions to this file: 
https://github.com/kevinpapst/kimai2/blob/master/templates/macros/actions.html.twig

**Comment by bjoerne2** [comment]
@kevinpapst I added some actions, see PR https://github.com/kevinpapst/kimai2/pull/757

Should be add more divider to the menus, e.g.

Edit
_
*Links to children*
_
*Links to create forms*
_
Delete


?

**Comment by kevinpapst** [comment]
Hm, maybe between the edit and link states:
```
Edit
_
Links to children
Links to other children
_
Delete
```
I think I have to see that. But then we would need to add some special logic for divider, which might be unnecessary?!

I'd say: lets be agile and wait for feedback first.

**Comment by rarvin** [comment]
I could see this under the more actions, but there is a small problem. I fell atleast the task active icon should be retained. Since now under the timesheet view it becomes really difficulty to know if the task is still active. But still one can find out which one is active since the end field would not be populated but earlier it was easier to find out which one was active. Having one or two icons like restart/stop would be good, rest all like restart/stop with description, edit and remove can all be within actions. This would give you the flexibility to keep adding more actions easily.

**Comment by kevinpapst** [comment]
@rarvin we discuss that and decided against it. There are multiple ways to filter open records, especially via the global "active menu" dropdown in the top. The admin view is a different topic (but there is the "active" filter.
 
This feature request is implemented with #746 => closing. Thanks @bjoerne2
