### ISSUE TITLE
Show duration while creating new time entry

### ISSUE THREAD

**Issue by StefanWinterberger** [kevinpapst/kimai2#818]
**Is your feature request related to a problem? Please describe.**
Not a problem. More a usability issue.

**Describe the solution you'd like**
While i'm creating a new time entry, it would be nice if I see directly the calculated duration, as soon as i have entered start and end time. This way I can see very quick if you entered the right start/end times.

**Comment by lduer** [comment]
I think this issue is already solved, as the duration field is automatically added - see: https://github.com/kevinpapst/kimai2/blob/master/src/Form/TimesheetEditForm.php#L122

@kevinpapst: But now, I personally don't want to show the duration field. Is it intended to add a configuration option here? Normally I'd add a simple CSS-hide, but further on, the size/length of the form-fields itself are depending from the insertion of the duration field. What is the best solution? :)

**Comment by kevinpapst** [comment]
Thanks @lduer its hard to keep the issues up-to-date... 

Well, you could switch to another time tracking mode, but I guess that's not what you want?
Why do you want to remove it in the first place? I never felt that I would need it, but after I added it, I figured that that is is really helping.

Seems I need to have a closer look at the underlying display logic, as the duration field should be relying on the `allow_duration` [option](https://github.com/kevinpapst/kimai2/blob/master/src/Form/TimesheetEditForm.php#L116), which is defined in the tracking mode, eg. here: https://github.com/kevinpapst/kimai2/blob/master/src/Timesheet/TrackingMode/DefaultMode.php#L41

**Comment by lduer** [comment]
Reason: mobile use. Most of my users access kimai by smartphone, and IMHO (and after evaluating the fist year of using it) each field which can be "hidden" is better for usability.

The [Line 122](https://github.com/kevinpapst/kimai2/blob/master/src/Form/TimesheetEditForm.php#L122) is outside the `allow_duration` check.

I have another Idea for advanced customizations without code edits, but I'll open another issue for that.
