### ISSUE TITLE
Invoice calculator that differs between fixed and hourly rates

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#884]
**Is your feature request related to a problem? Please describe.**
We have many timesheets with services to be calculated on basis of an hourly rate as well as costs at a 'fixed rate'. When creating invoices, it is not possible to differentiate between the two (the template company.doc cannot handle a mixture of fixed and hourly rates, if the option 'hours added up - only one entry' is used) 

**Describe the solution you'd like**
An option were very much appreciated to list two lines in the invoice, one line showing the added up hours of service (at an hourly rate) and a second line showing the costs/items to be calculated at a fixed rate.

**Comment by kevinpapst** [comment]
Can you please do not mix multiple issues in one.

1. What you need to create your own invoice template to achieve the desired result?
2. What exactly does not work? I need a working test case that I can easily understand.

**Comment by BeckeBauer** [comment]
Sorry for the confusion. To better understand the issue, let me give you an example:
Let`s say we provide services for a customer at a rate of 100 Euro / hour.
Part of the service are costs for material.
The invoice settings are the Kimai "company.doc" as template and as sum calculation "hours added up - only one entry". 

I create an entry for services for 30 minutes (=50 Euro).
I create an entry for material costs at a fixed rate of 20 Euro.

Now, I have Kimai create the invoice for this customer which I have attached. Although the total amount is correctly calculated, only one entry does not reflect the situation correctly.

Therefore, if timesheet entries at a fixed rate and entries at an hourly rate are mixed for one customer, two lines were required in an "hours added up" invoice scenario: one line for added up hours provided at an hourly rate and a second line for added up hours provided at a fixed rate. 
[company.docx](https://github.com/kevinpapst/kimai2/files/3341732/company.docx)

**Comment by kevinpapst** [comment]
Me:
> hours added up - only one entry

You:
> one line for added up hours provided at an hourly rate and a second line for added up hours provided at a fixed rate

Let me highlight it: **only one entry** vs **and a second line**😃 

You want something else to happen in that special case. 
But I will **not** change the behavior, as it would break invoices of all the people out there using it as is.

You want that Kimai:
- can handle expenses, but that something totally different than having an invoice calculator magically changing its behavior
- offers a new invoice calculator that differs between fixed and hourly rates 

I take this as a feature request for the latter point.

**Comment by BeckeBauer** [comment]
Thanks for the clarification although I disagree that there are users having it productive in the described way (since the invoices were simply not correct).

But you made clear that discussions will not help. So, to phrase a feature request: Could there be an option to add non-timebased entry (just with a date) that will be shown on the invoice in an additional line, no matter if the time-based entries are listed or added up in one line.

**Comment by kevinpapst** [comment]
I missed the attachment. The problem is not that I don't want to discuss: I have to spent at least 15 minutes for each issue only to verify it and sometimes I just don't understand the problem.
In that case a screenshot can show the problem immediately:
<img width="608" alt="Bildschirmfoto 2019-06-30 um 15 56 12" src="https://user-images.githubusercontent.com/533162/60397671-9b325700-9b4f-11e9-8b8c-d7b3e7dc23fb.png">

Thanks for your feedback! Without you insisting I would not have understood the problem.

> But I will not change the behavior, as it would break invoices of all the people out there using it as is.

Nevertheless I still stick with that. Meaning: I am not going to change the behavior and introduce a second line for fixed rates (or unlimited more rows, as you can have different fixed rates in different rows). 
That has nothing todo with my will for discussion: but a calculator that should create one row, might not create multiple rows, it just doesn't make sense.

But I fixed the original problem in #891 and your example would now look like this:
<img width="603" alt="Bildschirmfoto 2019-06-30 um 16 10 39" src="https://user-images.githubusercontent.com/533162/60397861-d7ff4d80-9b51-11e9-9710-95dea87af82b.png">

In the future I will work on expense tracking, that will solve your feature request. 
Until then, if you still need it after the fix, please open a new feature request for a invoice calculator that separates hourly rates and fixed rates. And please include how the entry grouping should work.

**Comment by BeckeBauer** [comment]
Thank you 👍
