### ISSUE TITLE
Unknown database type enum requested when updating to 1.0.1

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#923]
Hi Kevin,

I have updated the composer and checkout 1.0.1. After this I was able to do the update using the described procedure:

> git fetch --tags

> git checkout 1.0.1

> composer install --no-dev --optimize-autoloader

This works without any problems :-)

Unfortunately I run into a severe problem during database migration:

> web1171@ssh:/var/www/web1171/html/kimai2$ php bin/console doctrine:migrations:migrate

                    Application Migrations

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20190617100845 from 20190321181243

  ++ migrating 20190502161758 (Creates the color columns on: customer, project, activity)

Migration 20190502161758 failed during Execution. Error Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
20:03:49 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate". Message: "Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it." ["exception" => Doctrine\DBAL\DBALException { …},"command" => "doctrine:migrations:migrate","message" => "Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it."]

In AbstractPlatform.php line 434:

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

> 

I have MySQl 5.7.25.

Regards,
Ralf

_Originally posted by @ralfboernemeier in https://github.com/kevinpapst/kimai2/issues/910#issuecomment-508830972_

**Comment by kevinpapst** [comment]
@ralfb
Haven't used MySQL in a long time, all I can say: I don't use enum fields.
Here is the CI build with MariaDB: https://travis-ci.org/kevinpapst/kimai2/jobs/554785521#L2907

Please edit this line https://github.com/kevinpapst/kimai2/blob/master/config/packages/doctrine.yaml#L17 and remove the initial `#` and then re-try:
```
server_version: '5.7'
```

**Comment by kevinpapst** [comment]
If it doesn't help, which I guess as the server was correctly detected, please show me the output of:
```sql
describe kimai2_activities;
describe kimai2_projects;
describe kimai2_customers;
```

**Comment by ralfboernemeier** [comment]
Hi Kevin,

as you expected, same error after changing doctrine.yaml.
Here are the requested output:

[describe_kimai2_projects.pdf](https://github.com/kevinpapst/kimai2/files/3363818/describe_kimai2_projects.pdf)
[describe_kimai2_customers.pdf](https://github.com/kevinpapst/kimai2/files/3363819/describe_kimai2_customers.pdf)
[describe_kimai2_activities.pdf](https://github.com/kevinpapst/kimai2/files/3363820/describe_kimai2_activities.pdf)

Regards,

Ralf

**Comment by kevinpapst** [comment]
And there is no enum inside, also as expected. This release drives me crazy 😠 
I am trying to setup an automated test with travis, so I am able to verify the problem in #924.
I'll come back when I know more.

**Comment by ralfboernemeier** [comment]
Thanks for your Support and effort on this.
I hope you will find a solution.

If you need infos from my site please let me know.

Regards,

Rallf

**Comment by kevinpapst** [comment]
It took me a while, but not the tests are working and all migrations are executed on the Travis also with MySQL 5.7.28, see here:
https://travis-ci.org/kevinpapst/kimai2/jobs/554900991#L616

And this is the successful migration executed in the same build:
https://travis-ci.org/kevinpapst/kimai2/jobs/554900991#L1009

As I said: there is no enum used.

**Comment by ralfboernemeier** [comment]
Hi Kevin,

Good news for you - the code works fine :-)
Bad news for me - the database seems to be corrupted :-( 

I see the following possibilities for me:

1. Forget the update and stay with 0.9.
2. Do a fresh Installation using 1.0.1 and hope that it will run as you have tested on Travis with MySQL 5.7.x.
3. Use the current updated kimai2 directory (1.0.1 from yesterday) and create a new database.

I don‘t like 1.) but it‘s a fallback - this means don‘t use 3.) because I need the database.
I think I will 1st try 2.) using a new database so I still have 1.) This will of cause create more work for me because I have to manually create the customers, activities and projects, but fortunately we are talking about <100 and not 1000 ;-)

Question:

Is there a way to create a new database (step 3.) without doing a complete new installation?
Are the logins stored in the database?

Thanks again for your work on this - great job!!

Regards,

Ralf

**Comment by kevinpapst** [comment]
Creating a new database is simple, just change the database name in your .env and run these steps: 
https://www.kimai.org/documentation/installation.html#database 

But I don't think should do either. 
I just said that I don't use enums and that the migrations seem to work with MySQL 5.7.
Lets try to find the problem...

Can you tell me: was 0.9 the initial installation or did you upgrade already from a previous version?

**Comment by ralfboernemeier** [comment]
I did an upgrade once, don‘t know exactly from which version, but 0.9 was not the initial installation.

Regards,

Ralf

**Comment by kevinpapst** [comment]
Can you share an database export, so I can test?

**Comment by ralfboernemeier** [comment]
For your information, I'm using kimai2 on an ISP web space and there are other tables in the database. I have done an export of the kimai2 tables --> see attachment. Due to the fact that there are customer names in the export, I have used a password for the ZIP archive. Can you please send me an email to ralf.boernemeier@ralfb-web.de and I will reply with the password? 

Regards,

Ralf
[usr_web1171_1_kimai2_tables.zip](https://github.com/kevinpapst/kimai2/files/3364721/usr_web1171_1_kimai2_tables.zip)

**Comment by kevinpapst** [comment]
This was fixed by importing the dump into MariaDB, executing the upgrade, exporting and transferring it back to mysql.

If someone has the same problem, I will re-open this issue, just leave a note.
