### ISSUE TITLE
Collecting ideas for custom-fields

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#957]
This issue should be a collection thread for your ideas regarding custom fields (and please include examples if possible).

**Comment by rarvin** [comment]
In our case the customer, project and activity are all static fields and the one thing that keeps changing is the articleID or the article name. In our case the work related to the articleID has to be booked against the customer, project and activity and this is what we do. Work is allocated to us from a booking system which gives us the article ID and now to link the timesheet to an article ID we currently map them to a tag, since they are exportable as well as can be used in the invoice. But the custom fields have an advantage since in our case we could use it exclusively for the article ID. Now an operator has identfied an article that they need to work, based on for 'what customer' the work has to be accounted for they choose the customer, find the milestone of work they are to complete (this is chosen in the project) and under the specific milestone they track the work to an activity. Now operators dont get the work done in one go. They stop tasks and restart them. But any task has a threshold within which the work has to be completed which is kind of like the SLA if someone is breaching that then one has to be notified. In our case if the custom filed has the value linked to an articleID and all timesheets that are linked to the article ID for a said activity should be completed within the SLA (time budget). We would like to know if a timesheet task linked grouped by an article id has gone over budget. 

Custom fields are not available in filtering but tags are, having them in filtering, grouping can help a lot.

**Comment by kevinpapst** [comment]
Let me re-phrase it, if I understand that correctly: you want a search field for the custom-fields?
That would mean at least two fields for filtering: one for the "custom field name" and one for the "value", right?

What do you mean by grouping?

**Comment by rarvin** [comment]
> Let me re-phrase it, if I understand that correctly: you want a search field for the custom-fields?
> That would mean at least two fields for filtering: one for the "custom field name" and one for the "value", right?
yes you are correct
> What do you mean by grouping?
Right now grouping is not present, grouping would be something like that you have done for timebudget
Example 
Currently the activity Adding stage-DOC source in the project Alpha for the customer General has 56 time-records, which count up to a total of 41:53 h.
Once a new custom filed is created there would be similar entries in the custom field, would like to see aggregrated results grouped by the distinct values in them.

**Comment by rarvin** [comment]
When restarting the timesheet the custom fields data to be also copied automatically. This is also needed. :)

**Comment by rarvin** [comment]
Can custom fields be extended to users also. There are user specific data that might need to be stored.

**Comment by kevinpapst** [comment]
Thats already possible via user-preferences:
https://www.kimai.org/documentation/user-preferences.html#adding-new-userpreference

**Comment by cbellersen** [comment]
Here are some ideas: 

Most of our work is organized by two issue tracking software (Mantis for our own projects and Jira for our largest customer). We do technical support and most tickets have less then 2 hrs of effort, so creating a project in Kimai2 would not be reasonable. 
Our support staff always writes the ticket id at the beginning of a time tracking comment. So what we would like to use custom fields for, would be the "ticket id". Two features would be super: 

1. a view to see the total time booked per custom field value (eg. how much time has been booked for ticket id 12345)

2. a webhook to call back a URL after time has been booked on a custom field with parameters: the value of the custom field and some time tracking info (start date, end date, hours booked, timesheet-id)

3. make custom fields available per project in Kimai2. This way we could create one field "Jira ticket id", which is assigned to some projects and "Mantis ticket id", which is assigned to other projects. This would give us the ability to have two different Webhooks for Jira and Mantis.

**Comment by kevinpapst** [comment]
1. Reporting and filtering by custom field is a good idea, which @rarvin also mentioned.
2. Interesting idea. Not sure if that should be a "by custom field" webhook, or a general event webhook. The receiver should filter the payload and check if something should be done. Please open a new feature request for webhooks.
3. Thats already possible. See https://www.kimai.org/documentation/meta-fields.html and  https://www.kimai.org/store/custom-fields-bundle.html

**Comment by rarvin** [comment]
Custom fields do not allow a list of values to be made available to the user. If this is available then users could be guided to choose one among the available values for that specific field. This would be a nice add on for custom fields for all.

**Comment by rarvin** [comment]
Can there be some custom fields which are not mandatory when creating a timesheet record but are mandatory when the timesheet record is stopped. Like when a timesheet record is stopped if there is a mandatory field to be entered it should pop up asking the user to enter or choose the required values and only then should the next task be allowed to started.

**Comment by kevinpapst** [comment]
Okay, having a "collecting ideas" issue was a bad idea. Now a lot of requests are here and the issue can never be closed ;-)

Filtering by custom field will be added with #1064 

@rarvin please open a new issue in the private repo for
> Custom fields do not allow a list of values to be made available to the user. If this is available then users could be guided to choose one among the available values for that specific field. This would be a nice add on for custom fields for all.

I will close this issue later, please open new (single) issues for the stuff that's important for you.

**Comment by kevinpapst** [comment]
Filtering by custom-fields is now available in master

**Comment by rarvin** [comment]
> Okay, having a "collecting ideas" issue was a bad idea. Now a lot of requests are here and the issue can never be closed ;-)
> 
> Filtering by custom field will be added with #1064
> 
> @rarvin please open a new issue in the private repo for
>
There is already an issue open 
https://github.com/kevinpapst/MetaFieldsBundle/issues/3
 
> > Custom fields do not allow a list of values to be made available to the user. If this is available then users could be guided to choose one among the available values for that specific field. This would be a nice add on for custom fields for all.
> 
> I will close this issue later, please open new (single) issues for the stuff that's important for you.
Sure I would open other issues
