### ISSUE TITLE
Minor: Currency upon NewProject

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#972]
if
`Create customer - default values  >> CURRENCY != EUR`
then
Creating a new project will show wrong currency (EUR), (but will take the right one anyway)

Hope this is not annoying, I just protocol stuff I find. OK?
If I get the chance I'd do a checklist. But I'm on another mission right now.

**Comment by kevinpapst** [comment]
> I just protocol stuff I find. OK?

Sure, thats great 👍

The correct currency is unknown at the time of creation (as it is bound to the customer), therefor the default currency should be used. Did you check if this is applied?
https://www.kimai.org/documentation/customer.html#creating-customer

**Comment by Elijha** [comment]
I noticed this also.

With settings in the local.yaml set and the settings in the application set I still see 'Euro' currency symbols 
- When a New Project is being created
- when a New Activity is being created

When creating a New Customer the currency symbol is updated and the location Currency selector is correctly defaulted to the settings (as well as the timezone and country).

When creating a new Time Sheet the Fixed Rate and Hourly rate inputs lack a currency prefix, neither as a default before selecting a client and not added or updated when the client is selected. When editing an existing Time entry the entry does load with the client assigned currency.
This may be intentional but just covering all the creation / currency places I have seen.

**Comment by kevinpapst** [comment]
Thanks for the details @Elijha 
That never occured to me, because I use € exclusively. 
I'll have a look how to improve that.
