### ISSUE TITLE
Show days instead of hours if activity takes longer than 24h

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#997]
We use your brilliant tool not only to record working time but also absent time (e.g. holidays of employees). In such cases, it would be more comprehensible if the timesheet record would show days for every exceeding 24h (e.g. 14 d instead 336:00 h as it is now). 

P.S.: An activity is attributed to the day when it begun. If you recorded, for instance, 14 holiday, the whole 336h are credited to the first day:
![screenshot1](https://user-images.githubusercontent.com/51003649/62228351-c6fa6400-b3bd-11e9-8120-2aaf27c1b00a.gif)

For holidays, it might not be a problem, but if a project would require an overnight stay which is to be charged to the customer, it might raise questions if more than 24 h are charged for just one project day and user. The solution would be to attribute only 24 h to the first day, 24 hours to the next day and so on until the last day of the project.

**Comment by kevinpapst** [comment]
Hmmm...

Well, adding a %day modifier to the duration format isn't a big issue for the timesheet lists.

Regarding holidays:
They should be tracked as single 8 hour bookings per day (or if the user has a half-day contract 4 hours...), even if that is quite annoying to enter right now. 
Thats how I will add in the future. Calculations might break if you log it differently.

Regarding overnight stays: 
What if three people work on the same day for the same customer. You might get more than two full days of work for one specific date. Thats a little bit different yes, but the same problem arises.

From my view the only place where this might be a real problem is invoices. What do you think? Or where do you see the real problems?

**Comment by BeckeBauer** [comment]
If it is a "real" problem is not me to judge. As I said, a "day modifier" would just ease to read a timesheet entry of more than 24 hours. 

In my view, a company would usually count holidays (not "holi-hours"). So, it does not matter if an employee works full-time or part time - in both cases, I would book the whole day (24h) for the employee as project / activity "holiday" (I admit it becomes difficult if you accepted half a day off but I would book it as 12 hours holiday). The same is true, if you recorded an "absence times due to sickness" project / activity. When I then list or export the records "holiday" (or "sickness"), it would help if the duration were shown as days instead of hours (of course, I can calculate with Excel the hours into days).

**Comment by BeckeBauer** [comment]
I was thinking again about the issue: showing days instead of hours might break the invoice logic. 
What might solve the conflict is to restrict a time record for one user to the day's end. So, in case that a user would record an activity let's say from 1.1. 11:00 to 3.1. 15:00, then kimai should create 3 entries:
1.1. 11:00 to 1.1. 23:59 duration 13 hours 
2.1. 00:00 to 2.1. 23:59 duration 24 hours 
3.1. 00:00 to 3.1. 15:00 duration 15 hours 
It would also make it easier to read the exported data in my case since there were not only one entry for the whole holiday period summed up in hours but one entry per (holi)day, so that it is a list with dates.

**Comment by kevinpapst** [comment]
Closing: handling holidays is a different topic and having records > 24h should normally not happen.
