### ISSUE TITLE
Feedback Upgrade 1.0 - 2.0

### ISSUE THREAD

**Issue by xentity** [kevinpapst/kimai2#998]
First of all: well done, big R E S P E C T.

To help to improve your work:

1. The version numbers are inconsistent. Sometimes 1.1 and sometimes 2.0 are used
2. The zip version seems to lack the bin directory, couldn't do the migration.
3. The git installation fails, if the owner of the directory is root, since the _vendor_ directory has to be installed, directories under public/bundles/ and the .env file has to be created. My workaround was to run the installation after _sudo chown -R www-data:www-data ._ in the kimai2 directory.
4. The installation does not check, if sqlite is available: Failed to import users: An exception occurred in driver: could not find driver. I installed _php-sqlite3_ to continue.

Additional hint: if one wants to run multiple console commands and the files belong to another user, one have to add the sudo -u www-data to **every** command, like this: 
`sudo -u www-data bin/console doctrine:schema:drop --force && sudo -u www-data bin/console doctrine:schema:create && sudo -u www-data bin/console kimai:import-v1 "mysql://kimai:kimai@127.0.0.1:3306/kimai?charset=utf8" "kimai_" "test1234" "DE" "EUR"`

**Comment by kevinpapst** [comment]
Hi!

Thanks for your feedback / input.

1. Can you show where 2.0 is written? This is **Kimai 2** in version **1.1**. If you never used Kimai 1 in the past, this might not make sense to you ;-) 
2. DON'T use the zip package if you have shell access. Never! Updates are not supported with the zip package. It is meant for the "poor FTP users" only.
3. Don't use root to install Kimai! It is not required and will very likely lead to troubles in the future. Either use www-data (as you did) or even better your own SSH user account and only change the permissions for the var folder afterwards. 
The www-data was in the documentation in the past and caused more harm than good. Therefor it was moved into the [FAQ section](https://www.kimai.org/documentation/installation.html#which-user-to-use-www-data-httpd-or-your-own).
4. Yes. As Kimai support SQLite and MySQL I only check for PDO. SQLite is available on all shared hosts that I have seen. If you run your own server, well then you are responsible for it^^ 
Checking for SQLite and MySQL because that would lead to much more false-negatives.

A documentation can never satisfy every user, thats why I decided to use the most simple commands. And actually they work on the servers I manage, using www-data is already a workaround which should be avoided if possible.

**Comment by xentity** [comment]
Hi,

1. e.g here: https://www.kimai.org/documentation/migration-v1.html, the db prefix is also kimai2. You're right, 2.0 is never mentioned. I used v1.3 so far. If I switch to kimai2 version 1.1, then this may misleading (and indeed, it is it for me).
2. OK
3. My procedure was: creating the git clone in /var/www requires root permitions, therefore the user and the group were root:root. I used the commands to set the right permissions (group www-data, etc.), which leaded also to permission issues. The user account way makes definitively more sense.
4. Thought, that if SQLite the default setting, the installation routine works out of the box. Doesn't have MariaDB/MySQL a coverage of 99.9% as well? Otherwise the tons of wordpress installations wouldn't work. Maybe a SQL server should be the default... my two cents.

Again, great work.

**Comment by kevinpapst** [comment]
Don't get me wrong. Discussion like these are very important!

1. Well, then this hopefully goes away soon, as I plan on releasing at least once a month. Only three month until 1.4 is higher than Kimai v1 ever was ;-) 
3. Hm, yes.maybe I could add a sentence about creating an empty directory for the "git clone" with sudo first and then giving permissions to the current user, so he can clone afterwards. 
But honestely: whatever I will write there, someone wil have problems with the installation. Thats for sure ;-)
4. Maybe I should really change away from SQLite being the default for GIT users. Might be the best solution, so everyone has to think about it. The ZIP package for FTP users could still use SQLite. Checking for pdo-mysql should rarely fail, thats true. There is only one user here that I know of, who rejects using MySQL and actively chooses to use SQLite. He might run into troubles then... 

I have to think about it for a while.
